"""Build the public estimates site (GitHub Pages) from published model outputs.

Usage:
  python scripts/build_site.py                 # regenerate site/ from site/data/
  python scripts/build_site.py --import-runs   # first copy fresh outputs from runs/

Two steps, on purpose. Model runs write to runs/ (gitignored, and the capital
gains run alone takes ~25 minutes against a local tax-unit cache), so CI can
never reproduce them. `--import-runs` copies a run's outputs into site/data/,
where they are committed and reviewed like code. Every page is then rendered
from those committed copies only, so the numbers in the prose, the charts, and
the downloadable CSVs cannot disagree, and `tests/test_site_build.py` can check
that the committed HTML is exactly what the committed data produces.

The .github/workflows/pages.yml workflow deploys site/ as-is; it does not build.

Pages are static HTML with CSS bar charts: no JavaScript, no external
requests beyond Google Fonts. Brand tokens are in site/assets/site.css.
"""
from __future__ import annotations

import argparse
import contextlib
import csv
import html
import json
import shutil
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SITE = REPO / "site"
DATA = SITE / "data"
REPO_URL = "https://github.com/Hawaii-Appleseed/Census-Forecaster"

GENERATED = "<!-- GENERATED by scripts/build_site.py from site/data/. Do not hand-edit. -->"

# Chart colors: brand teal-deep and teal.
C_PRIMARY = "#52796F"
C_SECOND = "#84A98C"


# ---------------------------------------------------------------------------
# data import
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Estimate:
    slug: str
    files: dict[str, str]   # published name in site/data/<slug>/ -> source path under runs/
    stamp: tuple[str, ...] = ()   # JSON manifests to stamp with published_at on import


CAPITAL_GAINS = Estimate(
    slug="capital-gains",
    files={f: f"cg_rate_options/{f}" for f in (
        "revenue_by_year.csv",
        "distribution_ty2027_act24.csv",
        "distribution_ty2026_act46.csv",
        "nonresident_addon.csv",
        "anchor_check.csv",
        "manifest.json",
    )},
    stamp=("manifest.json",),
)
ACT24 = Estimate(
    slug="act-24",
    files={
        "fiscal_by_scenario.csv": "sb3125_cd2_enhanced/enhanced.csv",
        "distribution_quintile.csv": "sb3125_cd2_enhanced/quintile.csv",
        "distribution_income_class.csv": "sb3125_cd2_enhanced/bracket.csv",
        "manifest.json": "sb3125_cd2_enhanced/manifest.json",
        # forecast_act24_vs_pre_act46.py writes no manifest; its provenance is
        # the script itself and SB3125_CD1_FORECAST.md's reconciliation section.
        "vs_pre_act46.csv": "act24_vs_pre_act46/decomposition.csv",
    },
    stamp=("manifest.json",),
)
WORKING_FAMILIES = Estimate(
    slug="working-family-credits",
    files={f: f"working_family_credits/{f}" for f in (
        "revenue_by_year.csv",
        "calibration.csv",
        "distribution_ty2028.csv",
        "by_family_type_ty2028.csv",
        "poverty_ty2028.csv",
        "manifest.json",
    )},
    stamp=("manifest.json",),
)
ESTIMATES = (ACT24, WORKING_FAMILIES, CAPITAL_GAINS)


def import_runs(est: Estimate) -> None:
    runs = REPO / "runs"
    missing = [src for src in est.files.values() if not (runs / src).exists()]
    if missing:
        raise SystemExit(f"runs/ is missing {missing}; run the model first.")
    dst = DATA / est.slug
    dst.mkdir(parents=True, exist_ok=True)
    for name, src in est.files.items():
        shutil.copy2(runs / src, dst / name)
    for name in est.stamp:
        manifest = json.loads((dst / name).read_text())
        manifest["published_at"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
        (dst / name).write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"imported {len(est.files)} files -> site/data/{est.slug}")


def read_csv(path: Path) -> list[dict]:
    with path.open(newline="") as fh:
        rows = list(csv.DictReader(fh))
    for r in rows:
        for k, v in r.items():
            with contextlib.suppress(TypeError, ValueError):
                r[k] = float(v)
    return rows


# ---------------------------------------------------------------------------
# formatting
# ---------------------------------------------------------------------------

def esc(s) -> str:
    return html.escape(str(s), quote=True)


def millions(v: float) -> str:
    """Prose: '$47 million'."""
    return f"${v:,.0f} million"


def m1(v: float) -> str:
    """Tables: millions to one decimal, with a true minus sign."""
    return f"{v:,.1f}".replace("-", "−")


def signed_dollars(v: float) -> str:
    """'+$1,075' / '−$58' / '$0' (true minus sign)."""
    if abs(v) < 0.5:
        return "$0"
    return f"{'+' if v > 0 else '−'}${abs(v):,.0f}"


def dollars(v: float) -> str:
    if v < 0.5:
        return "$0"
    return f"${v:,.0f}"


def pct(v: float, digits: int = 0) -> str:
    return f"{v:.{digits}f}"


def income_range(lo: float, hi: float, last: bool) -> str:
    def k(v):
        return f"${v / 1000:,.0f}K" if v < 1e6 else f"${v / 1e6:,.1f}M"
    if lo < 1:
        return f"Under {k(hi)}"
    if last:
        return f"{k(lo)} and up"
    return f"{k(lo)} to {k(hi)}"


def long_date(iso: str) -> str:
    d = datetime.fromisoformat(iso)
    return f"{d:%B} {d.day}, {d.year}"


# ---------------------------------------------------------------------------
# charts
#
# HTML/CSS bars rather than SVG: an SVG scales its text with the chart, so
# labels legible on a desktop shrink to ~7px on a phone. Bars sized in percent
# keep the text at its CSS size at every width. Each chart is one role="img"
# with a full-sentence aria-label; the data is also in a table or the CSVs.
# ---------------------------------------------------------------------------

Series = list[tuple[str, str, list[float]]]   # (name, color, values)


def _money_m(v: float) -> str:
    return f"${v:,.0f}M"


def hbar_chart(categories: list[str], series: Series, *, label: str, fmt=_money_m) -> str:
    """Horizontal grouped bars, value printed at each bar's end."""
    vmax = max(max(vals) for _, _, vals in series) or 1
    groups = []
    for i, cat in enumerate(categories):
        bars = "".join(
            f'<div class="ha-est__hbar-row"><span class="ha-est__hbar" '
            f'style="width:{max(100 * vals[i] / vmax, 0.4):.2f}%;background:{color}"></span>'
            f'<span class="ha-est__hbar-val">{esc(fmt(vals[i]))}</span></div>'
            for _, color, vals in series)
        groups.append(f'<div class="ha-est__hbar-group"><div class="ha-est__hbar-cat">{esc(cat)}</div>'
                      f'<div class="ha-est__hbar-bars">{bars}</div></div>')
    return (f'<div class="ha-est__chart ha-est__chart--h" role="img" aria-label="{esc(label)}">'
            f'<div aria-hidden="true">{"".join(groups)}</div></div>')


def column_chart(categories: list[str], series: Series, *, label: str, fmt=_money_m) -> str:
    """Vertical grouped columns with a value label on each column."""
    vmax = max(max(vals) for _, _, vals in series) or 1
    slots = []
    for i, cat in enumerate(categories):
        cols = "".join(
            f'<div class="ha-est__col"><span class="ha-est__col-val">{esc(fmt(vals[i]))}</span>'
            f'<span class="ha-est__col-bar" style="height:{100 * vals[i] / vmax:.2f}%;background:{color}"></span></div>'
            for _, color, vals in series)
        slots.append(f'<div class="ha-est__col-slot"><div class="ha-est__col-bars">{cols}</div>'
                     f'<div class="ha-est__col-cat">{esc(cat)}</div></div>')
    return (f'<div class="ha-est__chart ha-est__chart--v" role="img" aria-label="{esc(label)}">'
            f'<div class="ha-est__col-grid" aria-hidden="true">{"".join(slots)}</div></div>')

def stacked_column_chart(categories: list[str], series: Series, *, label: str, fmt=_money_m) -> str:
    """One column per category, series stacked bottom-up, total printed on top.
    Values must be non-negative."""
    totals = [sum(vals[i] for _, _, vals in series) for i in range(len(categories))]
    vmax = max(totals) or 1
    slots = []
    for i, cat in enumerate(categories):
        segs = "".join(
            f'<span class="ha-est__col-bar ha-est__col-seg" style="height:{100 * vals[i] / (totals[i] or 1):.2f}%;background:{color}"></span>'
            for _, color, vals in reversed(series))      # top-down in the DOM, so the first series ends up at the bottom
        slots.append(f'<div class="ha-est__col-slot"><div class="ha-est__col-bars">'
                     f'<div class="ha-est__col ha-est__col--stack"><span class="ha-est__col-val">{esc(fmt(totals[i]))}</span>'
                     f'<div class="ha-est__col-stack" style="height:{100 * totals[i] / vmax:.2f}%">{segs}</div></div>'
                     f'</div><div class="ha-est__col-cat">{esc(cat)}</div></div>')
    return (f'<div class="ha-est__chart ha-est__chart--v" role="img" aria-label="{esc(label)}">'
            f'<div class="ha-est__col-grid" aria-hidden="true">{"".join(slots)}</div></div>')


def diverging_bar_chart(categories: list[str], values: list[float], *, label: str, fmt,
                        pos_color: str = C_PRIMARY, neg_color: str = C_SECOND) -> str:
    """Single-series horizontal bars around a zero axis: negatives run left,
    positives right. The axis sits where the data's range puts it."""
    lo, hi = min(0.0, *values), max(0.0, *values)
    span = (hi - lo) or 1
    zero = 100 * -lo / span                      # axis position, % from the left
    rows = []
    for cat, v in zip(categories, values, strict=True):
        w = 100 * abs(v) / span
        left = zero if v >= 0 else zero - w
        color = pos_color if v >= 0 else neg_color
        side = "pos" if v >= 0 else "neg"
        rows.append(
            f'<div class="ha-est__div-row"><div class="ha-est__hbar-cat">{esc(cat)}</div>'
            f'<div class="ha-est__div-track"><span class="ha-est__div-axis" style="left:{zero:.2f}%"></span>'
            f'<span class="ha-est__div-bar" style="left:{left:.2f}%;width:{max(w, 0.3):.2f}%;background:{color}"></span>'
            f'<span class="ha-est__div-val ha-est__div-val--{side}" style="{"left" if v >= 0 else "right"}:'
            f'{(zero + w) if v >= 0 else (100 - zero + w):.2f}%">{esc(fmt(v))}</span></div></div>')
    return (f'<div class="ha-est__chart" role="img" aria-label="{esc(label)}">'
            f'<div aria-hidden="true">{"".join(rows)}</div></div>')


def legend(series: list[tuple[str, str, list[float]]]) -> str:
    items = "".join(f'<span><span class="ha-est__swatch" style="background:{c}"></span>{esc(n)}</span>'
                    for n, c, _ in series)
    return f'<div class="ha-est__legend" aria-hidden="true">{items}</div>'


def figure(num: int, caption: str, chart: str, source: str, series=None, note_ref: str = "") -> str:
    leg = legend(series) if series else ""
    return (f'<figure class="ha-est__figure" id="figure-{num}">'
            f'<p class="ha-est__figcap">Figure {num}. {caption}{note_ref}</p>{leg}{chart}'
            f'<p class="ha-est__source">{source}</p></figure>')


def table(headers: list[str], rows: list[list[str]], *, caption: str, em_rows: set[int] = frozenset()) -> str:
    th = "".join(f'<th scope="col">{h}</th>' for h in headers)
    body = []
    for i, r in enumerate(rows):
        cls = ' class="ha-est__row-em"' if i in em_rows else ""
        cells = "".join((f'<th scope="row">{c}</th>' if k == 0 else f"<td>{c}</td>") for k, c in enumerate(r))
        body.append(f"<tr{cls}>{cells}</tr>")
    # Caption sits outside the scroll wrapper so a wide table scrolls without clipping it.
    return (f'<p class="ha-est__figcap">{caption}</p><div class="ha-est__table-wrap">'
            f'<table><thead><tr>{th}</tr></thead><tbody>{"".join(body)}</tbody></table></div>')


# ---------------------------------------------------------------------------
# page shell
# ---------------------------------------------------------------------------

def page(*, title: str, description: str, body: str, depth: int, year: int) -> str:
    up = "../" * depth
    return f"""<!DOCTYPE html>
{GENERATED}
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(title)}</title>
<meta name="description" content="{esc(description)}">
<meta property="og:title" content="{esc(title)}">
<meta property="og:description" content="{esc(description)}">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Manrope:wght@500;600;700;800&family=Poppins:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500&display=swap">
<link rel="stylesheet" href="{up}assets/okina.css">
<link rel="stylesheet" href="{up}assets/site.css">
</head>
<body class="ha-est">
<header class="ha-est__nav"><div class="ha-est__nav-inner">
<a href="https://www.hiappleseed.org"><img src="{up}assets/appleseed-logo-cropped.png" alt="Hawaiʻi Appleseed Center for Law &amp; Economic Justice"></a>
<a class="ha-est__nav-link" href="{up}index.html">All estimates</a>
</div></header>
<main>
{body}
</main>
<footer class="ha-est__footer"><div class="ha-est__footer-inner">
<img src="{up}assets/appleseed-footer-logo-white.png" alt="Hawaiʻi Appleseed">
<p>Estimates from Hawaiʻi Appleseed’s open-source tax and census models. Code, data, and methodology: <a href="{REPO_URL}">{REPO_URL.removeprefix("https://")}</a>.</p>
<p>Copyright © {year} Hawaiʻi Appleseed Center for Law &amp; Economic Justice. All rights reserved. 733 Bishop Street, Suite 1180, Honolulu, HI 96813</p>
</div></footer>
</body>
</html>
"""


def section(heading: str, body: str, sid: str) -> str:
    return (f'<section class="ha-est__section" id="{sid}"><div class="ha-est__section-inner">'
            f'<h2>{heading}</h2><hr class="ha-est__h2-rule">{body}</div></section>')


def lead(words: str, rest: str) -> str:
    """The house lead-in: a section's first few words set in caps."""
    return f'<p><span class="ha-est__lead-in">{words.upper()}</span> {rest}</p>'


class Notes:
    """Numbered endnotes; `ref` returns the superscript marker."""

    def __init__(self):
        self.items: list[str] = []

    def ref(self, text: str) -> str:
        if text in self.items:          # repeat cite: same number, no second anchor id
            n = self.items.index(text) + 1
            return f'<sup><a href="#note-{n}">{n}</a></sup>'
        self.items.append(text)
        n = len(self.items)
        return f'<sup><a href="#note-{n}" id="ref-{n}">{n}</a></sup>'

    def html(self) -> str:
        lis = "".join(f'<li id="note-{i}">{t}</li>' for i, t in enumerate(self.items, 1))
        return f'<ol class="ha-est__endnotes">{lis}</ol>'


# ---------------------------------------------------------------------------
# capital gains page
# ---------------------------------------------------------------------------

GROUPS_SHORT = {"Lowest 20%": "Lowest 20 percent", "Second 20%": "Second 20 percent",
                "Middle 20%": "Middle 20 percent", "Fourth 20%": "Fourth 20 percent",
                "Next 15%": "Next 15 percent", "Next 4%": "Next 4 percent", "Top 1%": "Top 1 percent"}


def _rev(rows, year, law, option, variant="central"):
    for r in rows:
        if (int(r["tax_year"]), r["law"], r["option"], r["top_share"]) == (year, law, option, variant):
            return r
    raise KeyError((year, law, option, variant))


def _nr(rows, year, option, kind):
    for r in rows:
        if (int(r["tax_year"]), r["option"], r["kind"]) == (year, option, kind):
            return r
    raise KeyError((year, option, kind))


def build_capital_gains() -> tuple[str, dict]:
    d = DATA / CAPITAL_GAINS.slug
    rev = read_csv(d / "revenue_by_year.csv")
    dist = read_csv(d / "distribution_ty2027_act24.csv")
    nr = read_csv(d / "nonresident_addon.csv")
    manifest = json.loads((d / "manifest.json").read_text())
    p = manifest["params"]
    notes = Notes()

    Y = 2027
    years = sorted({int(r["tax_year"]) for r in rev if r["law"] == "act24"})
    cap_new = p["options"]["cap9"] * 100
    cap_cur = p["cap_current"] * 100
    beta = p["beta"]

    c9 = _rev(rev, Y, "act24", "cap9")
    od = _rev(rev, Y, "act24", "ordinary")
    c9_46 = _rev(rev, Y, "act46", "cap9")
    od_46 = _rev(rev, Y, "act46", "ordinary")
    od_lo = min(_rev(rev, Y, "act24", "ordinary", v)["behavioral_M"] for v in ("low", "model"))
    od_hi = max(_rev(rev, Y, "act24", "ordinary", v)["behavioral_M"] for v in ("low", "model"))
    c9_lo = min(_rev(rev, Y, "act24", "cap9", v)["behavioral_M"] for v in ("low", "model"))
    c9_hi = max(_rev(rev, Y, "act24", "cap9", v)["behavioral_M"] for v in ("low", "model"))
    t26 = {o: _rev(rev, 2026, "act46", o) for o in ("cap9", "ordinary")}
    itep = {"cap9": 44.0, "ordinary": 85.0}
    top = next(r for r in dist if r["group"] == "Top 1%")
    nxt4 = next(r for r in dist if r["group"] == "Next 4%")
    bottom60_zero = all(r["total_ordinary_behavioral_M"] < 0.005 for r in dist[:3])
    act24_effect = od["behavioral_M"] - od_46["behavioral_M"]
    nr_od = _nr(nr, Y, "ordinary", "behavioral")
    nr_c9 = _nr(nr, Y, "cap9", "behavioral")
    last = years[-1]
    od_last = _rev(rev, last, "act24", "ordinary")["behavioral_M"]
    c9_last = _rev(rev, last, "act24", "cap9")["behavioral_M"]

    T_act24 = (
        'Hawaiʻi State Legislature, “SB 3125 SD1 HD1 CD2,” enacted as Act 24, Session Laws of Hawaiʻi 2026, '
        'May 21, 2026. <a href="https://www.capitol.hawaii.gov/session/measure_indiv.aspx?billtype=SB&amp;billnumber=3125&amp;year=2026">'
        'capitol.hawaii.gov</a>')
    T_hrs = (
        'Hawaiʻi Revised Statutes §235-51(f), alternative tax on net capital gain. '
        '<a href="https://www.capitol.hawaii.gov/hrscurrent/Vol04_Ch0201-0257/HRS0235/HRS_0235-0051.htm">capitol.hawaii.gov</a>')
    T_blog = (
        'Thomas, Devin, “Hawaiʻi’s two-tier tax system: How the rich use a glaring loophole to pay less,” '
        'Hawaiʻi Appleseed Center for Law &amp; Economic Justice, November 13, 2025. '
        '<a href="https://www.hiappleseed.org/blog/hawaii-two-tier-tax-system-glaring-loophole-rich-pay-less">hiappleseed.org</a>. '
        'Its figures were produced by the Institute on Taxation and Economic Policy.')
    T_dotax = (
        'Hawaiʻi Department of Taxation, “Hawaiʻi Individual Income Tax Statistics,” tax years 2018 to 2022 editions, '
        'Tables 21, A-1 and A-8. <a href="https://tax.hawaii.gov/stats/">tax.hawaii.gov/stats</a>')
    T_code = (
        f'Hawaiʻi Appleseed, <code>forecast_cg_rate_options.py</code>, Census-Forecaster model, commit '
        f'<code>{esc(manifest["git_sha"])}</code>. <a href="{REPO_URL}/blob/main/forecast_cg_rate_options.py">github.com</a>')
    T_cbo = (
        f'Congressional Budget Office, economic projections, {esc(p["cbo_vintage"])} vintage, capital gains realizations, '
        'adjusted to Hawaiʻi. <a href="https://www.cbo.gov/topics/budget/economic-projections">cbo.gov</a>')

    src_model = (f"Source: Hawaiʻi Appleseed estimates, Census-Forecaster tax model; resident filers only; "
                 f"tax year {Y}.")

    # --- hero + stats
    hero = f"""
<section class="ha-est__hero"><div class="ha-est__hero-inner">
<p class="ha-est__eyebrow">Estimates · Capital gains</p>
<h1>Closing the Gap</h1>
<hr class="ha-est__hero-rule">
<p class="ha-est__deck">What Hawaiʻi would raise by taxing capital gains at {pct(cap_new)} percent, or at the same rates as wages, now that Act 24 has raised the top rate on work to 13 percent.</p>
<p class="ha-est__meta">Hawaiʻi Appleseed · Model run {esc(long_date(manifest["created_at"]))} · Tax years {years[0]} to {last}</p>
</div></section>
<div class="ha-est__stats">
<div class="ha-est__stat"><div class="ha-est__stat-num">{millions(od["behavioral_M"])}</div><div class="ha-est__stat-label"><strong>Tax gains as ordinary income.</strong> Revenue in tax year {Y}, residents.</div></div>
<div class="ha-est__stat"><div class="ha-est__stat-num">{millions(c9["behavioral_M"])}</div><div class="ha-est__stat-label"><strong>Raise the cap to {pct(cap_new)} percent.</strong> Revenue in tax year {Y}, residents.</div></div>
<div class="ha-est__stat"><div class="ha-est__stat-num">{pct(top["share_ordinary_behavioral"] * 100)} percent</div><div class="ha-est__stat-label">Share of the ordinary-rates increase paid by the <strong>top 1 percent</strong> of households.</div></div>
<div class="ha-est__stat"><div class="ha-est__stat-num">{13 - cap_cur:.2f} points</div><div class="ha-est__stat-label">Gap between the top rate on wages and the rate on capital gains under <strong>Act 24</strong>.</div></div>
</div>"""

    # --- section 1: the gap
    s1_series = [("Act 46 brackets", C_SECOND, [c9_46["behavioral_M"], od_46["behavioral_M"]]),
                 ("Act 24 brackets", C_PRIMARY, [c9["behavioral_M"], od["behavioral_M"]])]
    s1 = section("The Gap Act 24 Widened", f"""
{lead("Hawaiʻi taxes most income", f"on a graduated schedule, but long-term capital gains get a special ceiling. Under the alternative tax in state law, net capital gains are taxed at no more than {pct(cap_cur, 2)} percent, however high the filer’s other income.{notes.ref(T_hrs)}")}
<p>Act 24 of 2026 added a 13 percent bracket above $1 million of taxable income for joint filers ($750,000 for heads of household, $500,000 for single filers) and raised the rates between $350,000 and $1 million.{notes.ref(T_act24)} It left the capital gains ceiling where it was. The distance between the top rate on wages and the rate on capital gains therefore grew from 3.75 points to 5.75 points.</p>
<p>That matters for what closing the gap would raise. Taxing gains at ordinary rates now brings gains up to 13 percent rather than 11 percent, so the same option is worth more under Act 24 than it was under the Act 46 brackets it replaced. Figure 1 compares the two. A {pct(cap_new)} percent cap is nearly unchanged, because it does not depend on the ordinary rates.</p>
{figure(1, f"Revenue From Each Option Under Act 46 and Act 24 Brackets, Hawaiʻi (Tax Year {Y})",
        hbar_chart([f"{pct(cap_new)} percent cap", "Ordinary rates"], s1_series, label=f"Tax year {Y} revenue by bracket schedule: 9 percent cap {m1(c9_46['behavioral_M'])} million under Act 46 and {m1(c9['behavioral_M'])} million under Act 24; ordinary rates {m1(od_46['behavioral_M'])} million under Act 46 and {m1(od['behavioral_M'])} million under Act 24."),
        src_model + " Millions of dollars, with a realization response.", s1_series, notes.ref(T_code))}
<p>Under Act 24, taxing capital gains as ordinary income would raise about {millions(act24_effect)} more in tax year {Y} than the same change would have under the Act 46 brackets.</p>
""", "gap")

    # --- section 2: revenue
    s2_series = [(f"{pct(cap_new)} percent cap", C_SECOND, [_rev(rev, y, "act24", "cap9")["behavioral_M"] for y in years]),
                 ("Ordinary rates", C_PRIMARY, [_rev(rev, y, "act24", "ordinary")["behavioral_M"] for y in years])]
    rows = []
    for y in years:
        a, b = _rev(rev, y, "act24", "cap9"), _rev(rev, y, "act24", "ordinary")
        rows.append([str(y), m1(a["static_M"]), m1(a["behavioral_M"]), m1(b["static_M"]), m1(b["behavioral_M"])])
    s2 = section("What Each Option Would Raise", f"""
{lead("Taxing capital gains as ordinary income", f"would raise an estimated {millions(od['behavioral_M'])} from Hawaiʻi residents in tax year {Y}, the first year a bill passed in 2027 could reach. Raising the ceiling to {pct(cap_new)} percent would raise about {millions(c9['behavioral_M'])}.")}
<p>Both figures account for investors selling less when the tax on selling rises. The model reduces realized gains by {beta:.0f} percent for each point the state rate goes up. Without that response, the estimates would be {millions(od['static_M'])} and {millions(c9['static_M'])}. Figure 2 shows how revenue grows through {last} as gains grow with the economy.{notes.ref(T_cbo)}</p>
{figure(2, f"Revenue by Tax Year Under Act 24, Hawaiʻi ({years[0]} to {last})",
        column_chart([str(y) for y in years], s2_series, label=f"Revenue by tax year under Act 24. Ordinary rates rise from {m1(od['behavioral_M'])} million in {Y} to {m1(od_last)} million in {last}; the {pct(cap_new)} percent cap rises from {m1(c9['behavioral_M'])} million to {m1(c9_last)} million."),
        "Source: Hawaiʻi Appleseed estimates, Census-Forecaster tax model; resident filers only. Millions of dollars, with a realization response.", s2_series)}
{table(["Tax year", f"{pct(cap_new)}% cap, static", f"{pct(cap_new)}% cap, with response", "Ordinary, static", "Ordinary, with response"],
       rows, caption="Table 1. Resident Revenue by Tax Year Under Act 24 ($ Millions)", em_rows={0})}
<div class="ha-est__callout"><p><strong>How sure are these numbers?</strong> The biggest uncertainty is how gains split between filers just above and far above $1 million, since the top bracket applies only to the second group. State data puts about {p["top_share_variants"]["central"] * 100:.0f} percent of the gains in the top income class above $1 million. Moving that between {p["top_share_variants"]["low"] * 100:.0f} percent and the roughly 92 percent that national data implies gives a range of {millions(od_lo)} to {millions(od_hi)} for ordinary rates in {Y}, and {millions(c9_lo)} to {millions(c9_hi)} for the {pct(cap_new)} percent cap.</p></div>
""", "revenue")

    # --- section 3: distribution
    grp = [GROUPS_SHORT.get(r["group"], r["group"]) for r in dist]
    # The chart folds the bottom three quintiles into one bar when they pay nothing
    # (seven rows of 0.0% bury the point); Table 2 still lists every group.
    fold = 3 if bottom60_zero else 0
    chart_grp = (["Bottom 60 percent"] if fold else []) + grp[fold:]

    def _shares(col):
        vals = [r[col] * 100 for r in dist]
        return ([sum(vals[:fold])] if fold else []) + vals[fold:]
    s3_series = [(f"{pct(cap_new)} percent cap", C_SECOND, _shares("share_cap9_behavioral")),
                 ("Ordinary rates", C_PRIMARY, _shares("share_ordinary_behavioral"))]
    drows = []
    for i, r in enumerate(dist):
        drows.append([grp[i], income_range(r["tci_lo"], r["tci_hi"], i == len(dist) - 1), f"{r['households']:,.0f}",
                      dollars(r["avg_cap9_behavioral"]), dollars(r["avg_ordinary_behavioral"]),
                      pct(r["pct_hh_up_ordinary_behavioral"]), pct(r["share_ordinary_behavioral"] * 100, 1)])
    s3 = section("Who Would Pay", f"""
{lead("Almost all of the new revenue", f"would come from the highest-income households, because that is where capital gains are. Under ordinary rates, the top 1 percent of households, those with income above about {income_range(top['tci_lo'], 0, True).split(' ')[0]}, would pay {pct(top['share_ordinary_behavioral'] * 100)} percent of the increase, an average of {dollars(top['avg_ordinary_behavioral'])} each. The next 4 percent would pay {pct(nxt4['share_ordinary_behavioral'] * 100)} percent.")}
<p>{"Households in the bottom 60 percent would pay nothing more under either option: their income is taxed at rates below the " + pct(cap_cur, 2) + " percent ceiling, so the ceiling does not lower their tax today, and raising or repealing it changes nothing for them." if bottom60_zero else ""} Figure 3 shows each group’s share of the total, and Table 2 the average change per household.</p>
{figure(3, f"Share of the Tax Increase by Income Group, Hawaiʻi (Tax Year {Y})",
        hbar_chart(chart_grp, s3_series, label=f"Share of the tax increase by income group, tax year {Y}. The top 1 percent pays {pct(top['share_ordinary_behavioral'] * 100)} percent under ordinary rates.", fmt=lambda v: f"{v:.1f}%", ),
        src_model + " Groups rank all resident households by income; each holds the stated share of households.", s3_series)}
{table(["Income group", "Income range", "Households", f"Avg. change, {pct(cap_new)}% cap", "Avg. change, ordinary", "Percent with increase (ordinary)", "Share of total (ordinary, percent)"],
       drows, caption=f"Table 2. Average Tax Change by Income Group Under Act 24, Tax Year {Y}")}
""", "who-pays")

    # --- section 4: check vs ITEP
    crow = [[f"{pct(cap_new)} percent cap", millions(itep["cap9"]), millions(t26["cap9"]["static_M"]), millions(t26["cap9"]["behavioral_M"])],
            ["Ordinary rates", millions(itep["ordinary"]), millions(t26["ordinary"]["static_M"]), millions(t26["ordinary"]["behavioral_M"])]]
    s4 = section("Checking Against Earlier Estimates", f"""
{lead("In November 2025,", f"Hawaiʻi Appleseed published estimates from the Institute on Taxation and Economic Policy for the same two options, for tax year 2026 under the Act 46 brackets then in law: {millions(itep['cap9'])} for a {pct(cap_new)} percent cap and {millions(itep['ordinary'])} for ordinary rates.{notes.ref(T_blog)}")}
<p>Scored on the same year and brackets, this model lands within a few million dollars of both once the realization response is included, as Table 3 shows. That agreement is the basis for trusting the Act 24 estimates above, which use the same method with the new brackets.</p>
{table(["Option", "ITEP (2025)", "This model, static", "This model, with response"], crow,
       caption="Table 3. Tax Year 2026 Resident Revenue Under Act 46 Brackets")}
""", "check")

    # --- section 5: nonresidents
    s5 = section("Gains Earned by Nonresidents", f"""
{lead("The figures above count residents only,", f"to match the earlier estimates. Nonresidents who sell Hawaiʻi property or hold interests in Hawaiʻi businesses also pay the alternative tax on those gains. In a typical year, the model estimates they would add about {millions(nr_od['typical_year_M'])} to the ordinary-rates option and {millions(nr_c9['typical_year_M'])} to the {pct(cap_new)} percent cap in tax year {Y}.")}
<p>Nonresident gains swing widely from year to year. At tax year 2022 levels, when nonresident gains spiked, the add-on would be {millions(nr_od['ty2022_level_M'])} and {millions(nr_c9['ty2022_level_M'])}. Both figures include the realization response.{notes.ref(T_dotax)}</p>
""", "nonresidents")

    # --- section 6: method + downloads
    base = manifest["inputs"]["tax_unit_cache"]
    s6 = section("How These Estimates Are Made", f"""
{lead("The model builds", f"a synthetic population of about {base['n_units']:,} Hawaiʻi tax units from the Census Bureau’s American Community Survey microdata ({esc(base['pums'])}), calibrated to state tax data and projected forward with Congressional Budget Office growth rates. Filers with income above $1 million, whom survey data miss, are added from IRS and state tax statistics.")}
<p>Capital gains are anchored to the Department of Taxation’s count of resident long-term gains eligible for the alternative rate, by income class, then grown each year.{notes.ref(T_dotax)} Tax is computed as the statute defines the alternative tax, not with the simple shortcut of taxing gains at the lower of the bracket rate and the ceiling. The realization response and the split of gains at the top are the two assumptions that move the estimates most, and both are stated above.</p>
<p>The full method, including every parameter, is documented in the source code.{notes.ref(T_code)}</p>
<h3 style="font-size:18px;margin:28px 0 10px">Download the data</h3>
<ul class="ha-est__downloads">
<li><a href="../data/capital-gains/revenue_by_year.csv"><code>revenue_by_year.csv</code></a> — revenue by tax year, bracket schedule, option and top-share assumption</li>
<li><a href="../data/capital-gains/distribution_ty2027_act24.csv"><code>distribution_ty2027_act24.csv</code></a> — tax change by income group, tax year 2027, Act 24</li>
<li><a href="../data/capital-gains/distribution_ty2026_act46.csv"><code>distribution_ty2026_act46.csv</code></a> — the same for tax year 2026 under Act 46</li>
<li><a href="../data/capital-gains/nonresident_addon.csv"><code>nonresident_addon.csv</code></a> — nonresident add-on by year and option</li>
<li><a href="../data/capital-gains/anchor_check.csv"><code>anchor_check.csv</code></a> — model gains against Department of Taxation targets, by income class</li>
<li><a href="../data/capital-gains/manifest.json"><code>manifest.json</code></a> — run parameters, input vintages and code version</li>
</ul>
""", "method")

    endnotes = section("Endnotes", notes.html(), "endnotes")
    body = hero + s1 + s2 + s3 + s4 + s5 + s6 + endnotes
    desc = (f"Taxing capital gains as ordinary income would raise about {millions(od['behavioral_M'])} from Hawaiʻi residents "
            f"in tax year {Y}; a {pct(cap_new)} percent cap about {millions(c9['behavioral_M'])}.")
    card = {
        "slug": CAPITAL_GAINS.slug,
        "category": "proposed",
        "eyebrow": "Capital gains",
        "title": "Closing the Gap",
        "text": f"What taxing capital gains at {pct(cap_new)} percent, or at ordinary rates, would raise under Act 24.",
        "stat": f"${c9['behavioral_M']:,.0f} to {millions(od['behavioral_M'])}",
        "stat_label": f"per year, tax year {Y}",
        "date": long_date(manifest["created_at"]),
        "year": datetime.fromisoformat(manifest["created_at"]).year,
    }
    html_out = page(title="Closing the Gap: Capital Gains Options | Hawaiʻi Appleseed Estimates",
                    description=desc, body=body, depth=1,
                    year=datetime.fromisoformat(manifest["created_at"]).year)
    return html_out, card


# ---------------------------------------------------------------------------
# Act 24 page
# ---------------------------------------------------------------------------

# Joint-filer rate changes, Act 46 schedule -> Act 24 (SB 3125 CD2), from the
# enacted bracket schedules (SB3125_CD1_FORECAST.md §3; CD1 and CD2 brackets are
# identical). Statute, not model output, so it lives here rather than in site/data.
# (taxable income band, Act 46 rate TY2027, Act 24 rate, Act 46 rate TY2029)
ACT24_MFJ_CHANGES = (
    ("$28,800 to $38,400", "3.20", "2.50", "3.20"),
    ("$38,400 to $48,000", "5.50", "5.00", "5.50"),
    ("$350,000 to $450,000", "7.90", "8.25", "7.60"),
    ("$450,000 to $550,000", "8.25", "9.00", "7.90"),
    ("$550,000 to $650,000", "9.00", "10.00", "8.25"),
    ("$650,000 to $1 million", "10.00", "11.00", "9.00 to 11.00"),
    ("Above $1 million", "11.00", "13.00", "11.00"),
)

QUINTILE_LABEL = {"Q1 (bottom 20%)": "Lowest 20 percent", "Q2": "Second 20 percent", "Q3": "Middle 20 percent",
                  "Q4": "Fourth 20 percent", "Q5 (top 20%)": "Top 20 percent"}


def _fiscal(rows, scenario, year):
    for r in rows:
        if r["scenario"] == scenario and int(r["tax_year"]) == year:
            return r
    raise KeyError((scenario, year))


def build_act24() -> tuple[str, dict]:
    d = DATA / ACT24.slug
    fis = read_csv(d / "fiscal_by_scenario.csv")
    quint = read_csv(d / "distribution_quintile.csv")
    klass = read_csv(d / "distribution_income_class.csv")
    pre = read_csv(d / "vs_pre_act46.csv")
    manifest = json.loads((d / "manifest.json").read_text())
    notes = Notes()

    years = sorted({int(r["tax_year"]) for r in fis})
    Y, last = years[0], years[-1]
    mid = {y: _fiscal(fis, "MID", y) for y in years}
    tot = {sc: sum(_fiscal(fis, sc, y)["total_impact_$M"] for y in years) for sc in ("LOW", "MID", "HIGH")}
    credit = {y: mid[y]["credit_total_$M"] for y in years}
    brk = {y: mid[y]["bracket_delta_post_$M"] for y in years}
    brk_static5 = sum(mid[y]["bracket_delta_static_$M"] for y in years)
    eti5 = sum(mid[y]["eti_response_$M"] for y in years)
    pte5 = sum(mid[y]["pte_shift_$M"] for y in years)
    reec5 = sum(mid[y]["reec_savings_$M"] for y in years)
    cgec5 = sum(mid[y]["cgec_savings_$M"] for y in years)
    tcra5 = sum(mid[y]["tcra_savings_$M"] for y in years)

    q = [r for r in quint if int(r["tax_year"]) == Y]
    q_top = q[-1]
    q_mid = [r for r in q if r["quintile"] == "Q3"][0]
    k = [r for r in klass if int(r["tax_year"]) == Y]
    k_1m = [r for r in k if r["income_bracket"] == "$1M+"][0]
    # Per-household credit changes are attributed to imputed claimants at DOTAX
    # claim rates (quintile_analysis.attribute_credit_loss), so averages include
    # them and the pay-more / pay-less shares count only claimants as losing.
    hh_all = sum(r["household_count"] for r in q)

    def hh_share(col):
        return sum(r["household_count"] * r[col] for r in q) / hh_all

    pay_less, pay_more, claimants = hh_share("pct_pay_less"), hh_share("pct_pay_more"), hh_share("pct_credit_claimant")
    credit_hh_m = sum(r["total_credit_loss_$M"] for r in q)
    loss_per_claimant = credit_hh_m * 1e6 / (hh_all * claimants / 100)
    credit_Y = credit[Y]

    p = {int(r["tax_year"]): r for r in pre}
    a46_last = -(p[last]["A_act46_banked_by_2026"] + p[last]["B_act46_remaining_phaseins"])
    c_last = p[last]["C_act24_increment"]

    T_act24 = ('Hawaiʻi State Legislature, “SB 3125 SD1 HD1 CD2,” enacted as Act 24, Session Laws of Hawaiʻi 2026, '
               'May 21, 2026. <a href="https://www.capitol.hawaii.gov/session/measure_indiv.aspx?billtype=SB&amp;billnumber=3125&amp;year=2026">'
               'capitol.hawaii.gov</a>')
    T_act46 = ('Hawaiʻi State Legislature, “HB 2404 HD1 SD1 CD1,” enacted as Act 46, Session Laws of Hawaiʻi 2024, June 3, 2024. '
               '<a href="https://www.capitol.hawaii.gov/session/measure_indiv.aspx?billtype=HB&amp;billnumber=2404&amp;year=2024">capitol.hawaii.gov</a>')
    T_dotax = ('Hawaiʻi Department of Taxation, Announcement No. 2026-06, on the Act 24 changes to the renewable '
               'energy technologies income tax credit, 2026. <a href="https://tax.hawaii.gov/">tax.hawaii.gov</a>')
    T_claims = ('Hawaiʻi Department of Taxation, “Tax Credits Claimed by Hawaiʻi Taxpayers,” Tax Year 2023, '
                'Tables 2, A-5 and A-6. <a href="https://tax.hawaii.gov/stats/">tax.hawaii.gov/stats</a>')
    T_code = (f'Hawaiʻi Appleseed, <code>forecast_sb3125_enhanced.py --cd 2</code>, Census-Forecaster model, commit '
              f'<code>{esc(manifest["git_sha"])}</code>. <a href="{REPO_URL}/blob/main/forecast_sb3125_enhanced.py">github.com</a>')
    T_doc = (f'Hawaiʻi Appleseed, “SB 3125 (enacted as Act 24, SLH 2026) — Hawaii Income Tax Fiscal Impact Forecast,” '
             f'methodology and results, Census-Forecaster model. <a href="{REPO_URL}/blob/main/SB3125_CD1_FORECAST.md">github.com</a>')
    T_cor = ('Council on Revenues, General Fund forecast letter, May 21, 2026. '
             '<a href="https://tax.hawaii.gov/useful/a9_1cor/">tax.hawaii.gov</a>')
    T_pre = (f'Hawaiʻi Appleseed, <code>forecast_act24_vs_pre_act46.py</code>, Census-Forecaster model. '
             f'<a href="{REPO_URL}/blob/main/forecast_act24_vs_pre_act46.py">github.com</a>')

    src_model = "Source: Hawaiʻi Appleseed estimates, Census-Forecaster tax model; middle scenario."

    hero = f"""
<section class="ha-est__hero"><div class="ha-est__hero-inner">
<p class="ha-est__eyebrow">Current policy · Income tax</p>
<h1>Act 24</h1>
<hr class="ha-est__hero-rule">
<p class="ha-est__deck">How Hawaiʻi’s 2026 income tax law changes state revenue, and who pays more or less, compared with the Act 46 schedule it replaced.</p>
<p class="ha-est__meta">Hawaiʻi Appleseed · Model run {esc(long_date(manifest["created_at"]))} · Tax years {Y} to {last}</p>
</div></section>
<div class="ha-est__stats">
<div class="ha-est__stat"><div class="ha-est__stat-num">{millions(tot["MID"])}</div><div class="ha-est__stat-label"><strong>More revenue over five years,</strong> tax years {Y} to {last}, than Act 46 would have raised.</div></div>
<div class="ha-est__stat"><div class="ha-est__stat-num">{millions(mid[Y]["total_impact_$M"])}</div><div class="ha-est__stat-label">In <strong>tax year {Y},</strong> the first year the new brackets apply.</div></div>
<div class="ha-est__stat"><div class="ha-est__stat-num">{pct(pay_less)} percent</div><div class="ha-est__stat-label">Of households <strong>pay less</strong> income tax in {Y} than under Act 46.</div></div>
<div class="ha-est__stat"><div class="ha-est__stat-num">{dollars(k_1m["avg_per_hh_total_change"])}</div><div class="ha-est__stat-label">Average increase for households with income <strong>above $1 million</strong> in {Y}.</div></div>
</div>"""

    def dist_row(label, r):
        return [label, f"{r['household_count']:,.0f}", signed_dollars(r["avg_per_hh_bracket_change"]),
                signed_dollars(r["avg_per_hh_credit_loss"]), signed_dollars(r["avg_per_hh_total_change"]),
                pct(r["pct_pay_less"]), pct(r["pct_pay_more"])]
    dist_head = ["Households", "Rate changes", "Credit changes", "Total", "Percent paying less", "Percent paying more"]
    krows = [dist_row(r["income_bracket"].replace("–", " to "), r) for r in k]
    s1 = section("What Act 24 Changed", f"""
{lead("Act 24 rewrote the income tax brackets", f"that Act 46 of 2024 had scheduled for the rest of the decade.{notes.ref(T_act24)}{notes.ref(T_act46)} It cut two rates that most working households pay and raised the rates on income above $350,000 for joint filers ($262,500 for heads of household, $175,000 for single filers), adding a 13 percent bracket above $1 million ($750,000 and $500,000).")}
<p>Table 1 shows the changes for joint filers. The lower-bracket cuts are the same in every year. The increases at the top grow in {Y + 2}, when Act 46 would have lowered those rates again and Act 24 holds them where they are.</p>
{table(["Taxable income (joint)", f"Act 46, {Y}", "Act 24", f"Act 46, {Y + 2}"],
       [[b, f"{a} percent", f"{n} percent", f"{c} percent"] for b, a, n, c in ACT24_MFJ_CHANGES],
       caption="Table 1. Tax Rates That Changed, Joint Filers")}
<p>Act 24 also capped, ended or repealed several tax credits. These estimates score the three largest changes. It caps the renewable energy technologies income tax credit at $40 million a year, limits it to filers with income under $175,000 (single) or $350,000 (joint), and ends new credits after tax year 2029.{notes.ref(T_dotax)} It ends the capital goods excise tax credit after tax year 2027 and speeds up the phase-out of the research activities credit.</p>
""", "changes")

    s2_series = [("Bracket changes", C_PRIMARY, [brk[y] for y in years]),
                 ("Credit changes", C_SECOND, [credit[y] for y in years])]
    fig1_label = "Act 24 revenue gain by tax year: " + ", ".join(
        f"{y} {m1(mid[y]['total_impact_$M'])} million" for y in years) + "."
    frows = []
    for y in years:
        r = mid[y]
        frows.append([str(y), m1(r["bracket_delta_static_$M"]), m1(r["eti_response_$M"]), m1(r["credit_total_$M"]),
                      m1(r["total_impact_$M"]), m1(_fiscal(fis, "LOW", y)["total_impact_$M"]), m1(_fiscal(fis, "HIGH", y)["total_impact_$M"])])
    frows.append(["Total", m1(brk_static5), m1(eti5), m1(reec5 + cgec5 + tcra5), m1(tot["MID"]), m1(tot["LOW"]), m1(tot["HIGH"])])
    s2 = section("What It Raises", f"""
{lead("Compared with Act 46,", f"Act 24 raises an estimated {millions(mid[Y]['total_impact_$M'])} in tax year {Y}, rising to {millions(mid[last]['total_impact_$M'])} by {last}, for {millions(tot['MID'])} over five years.{notes.ref(T_code)}")}
<p>Two pieces add up to that total, shown in Figure 1. The bracket changes raise {millions(sum(brk.values()))} over the five years after accounting for high-income filers reporting less income when rates rise. The credit changes save the state {millions(reec5 + cgec5 + tcra5)}, most of it from the renewable energy credit ({millions(reec5)}). Credit savings jump in {years[3]}, the first year no new renewable energy credits are allowed.</p>
{figure(1, f"Revenue Gain From Act 24 Compared With Act 46, Hawaiʻi ({Y} to {last})",
        stacked_column_chart([str(y) for y in years], s2_series,
                             label=fig1_label),
        src_model + " Millions of dollars. Bracket changes include the behavioral response.", s2_series)}
{table(["Tax year", "Brackets, static", "Behavioral response", "Credit changes", "Total (middle)", "Low scenario", "High scenario"],
       frows, caption="Table 2. Act 24 Revenue Compared With Act 46 ($ Millions)", em_rows={len(frows) - 1})}
<div class="ha-est__callout"><p><strong>How sure are these numbers?</strong> The low and high scenarios vary how strongly top earners respond to higher rates, how fast top incomes grow, and how much demand there is for the renewable energy credit. Over five years they range from {millions(tot['LOW'])} to {millions(tot['HIGH'])}. {"One channel is not yet in these figures: some business owners may pay tax through their business instead of on their own returns to avoid the new top rate, which would lower the bracket gain." if abs(pte5) < 0.5 else ""}</p></div>
""", "revenue")

    qcat = [QUINTILE_LABEL.get(r["quintile"], r["quintile"]) for r in q]
    qrows = [dist_row(QUINTILE_LABEL.get(r["quintile"], r["quintile"]), r) for r in q]
    s3 = section("Who Pays More and Who Pays Less", f"""
{lead("Most households pay a little less.", f"In tax year {Y}, {pct(pay_less)} percent of households owe less income tax under Act 24 than they would have under Act 46, mostly from the lower rates on income between about $29,000 and $48,000 of taxable income for joint filers. The middle 20 percent of households save an average of {dollars(-q_mid['avg_per_hh_total_change'])}.")}
<p>The increase falls on the top. Households with income above $1 million pay an average of {dollars(k_1m['avg_per_hh_total_change'])} more, and the top 20 percent as a group pay {millions(q_top['total_change_$M'])} more. Figure 2 shows the average change for each fifth of households, and Tables 3 and 4 break it down.</p>
{figure(2, f"Average Change in Income Tax per Household Under Act 24, Hawaiʻi (Tax Year {Y})",
        diverging_bar_chart(qcat, [r["avg_per_hh_total_change"] for r in q], fmt=signed_dollars,
                            label=f"Average change per household in tax year {Y}: " + "; ".join(f"{c} {signed_dollars(r['avg_per_hh_total_change'])}" for c, r in zip(qcat, q, strict=True)) + "."),
        src_model + " Rate and credit changes, before the behavioral response. Households are ranked by income; each group holds one fifth of households.")}
<p>The credit changes fall on the households that claim the credits, not on everyone. At 2023 claim rates, about {pct(claimants, 1)} percent of households claim the renewable energy or capital goods credit, from {pct(q[0]['pct_credit_claimant'], 1)} percent of the lowest fifth to {pct(q_top['pct_credit_claimant'], 1)} percent of the top fifth.{notes.ref(T_claims)} In {Y} they lose an average of {dollars(loss_per_claimant)} each, {millions(credit_hh_m)} in all; for some, that outweighs the rate cut, which is why {pct(pay_more, 1)} percent of households pay more. The other {millions(credit_Y - credit_hh_m)} of the year’s credit savings falls on corporations and other business filers and is not shown here.</p>
{table(["Household income"] + dist_head, qrows, caption=f"Table 3. Average Change in Income Tax by Fifth of Households, Tax Year {Y}")}
{table(["Income (AGI)"] + dist_head, krows, caption=f"Table 4. Average Change in Income Tax by Income, Tax Year {Y}")}
<p class="ha-est__source">Averages are over all households in each group, claimants or not. Credit changes are assigned to households by the Department of Taxation’s claim rates and average claims by income; a household’s chance of claiming sets its share. The department reports all claims above $200,000 of income as one class, so the credit change is the same for every income group above that. The 2031 figures, when no new renewable energy credits are allowed, are in the downloadable data.</p>
""", "who-pays")

    prows = [[str(y), m1(p[y]["A_act46_banked_by_2026"] + p[y]["B_act46_remaining_phaseins"]), m1(p[y]["C_act24_increment"]),
              m1(p[y]["total_vs_pre_act46"])] for y in years]
    s4 = section("Act 24 Against the Law Before Act 46", f"""
{lead("Act 24 is small next to the tax cut it amended.", f"Act 46 of 2024 raised the standard deduction and widened the brackets in steps through {last}. Measured against the law before Act 46, it will cost the state about {millions(a46_last)} a year by {last} on this model’s static estimate. Act 24 recovers {millions(c_last)} of that, about {pct(100 * c_last / a46_last)} percent.{notes.ref(T_pre)}")}
<p>This model’s estimate of Act 46’s cost runs 14 to 21 percent below the Department of Taxation’s own figure, $1.45 billion by fiscal year 2032, largely because survey data miss nonresident filers and some business income.{notes.ref(T_cor)} That gap largely cancels when comparing Act 24 with Act 46, since both are scored on the same population, which is why the estimates above use that comparison.{notes.ref(T_doc)}</p>
{table(["Tax year", "Act 46", "Act 24", "Both laws"], prows,
       caption="Table 5. Static Change in Income Tax Revenue Compared With Pre-Act 46 Law ($ Millions)")}
<p class="ha-est__source">Negative numbers are revenue the state gives up. Brackets, standard deduction and personal exemption only; no behavioral response or credit changes.</p>
""", "context")

    base = manifest["inputs"]["tax_units_cache"]
    s5 = section("How These Estimates Are Made", f"""
{lead("The model builds", f"a synthetic population of about {base['n_units']:,} Hawaiʻi tax units from the Census Bureau’s American Community Survey microdata ({esc(base['pums'])}), calibrated to Department of Taxation statistics, and computes each unit’s tax under both laws for every year. Filers with income above $1 million, whom survey data miss, are added from IRS and state tax statistics.")}
<p>High earners are assumed to report less taxable income when their rates rise, and a few to move away; those responses are in the bracket figures. The credit changes are scored against projected claims under the old rules, and the share falling on individual filers is assigned to households by the Department of Taxation’s claim rates by income. The middle scenario is the recommended one. The full method, every parameter and each revision are documented with the code.{notes.ref(T_doc)}</p>
<h3 style="font-size:18px;margin:28px 0 10px">Download the data</h3>
<ul class="ha-est__downloads">
<li><a href="../data/act-24/fiscal_by_scenario.csv"><code>fiscal_by_scenario.csv</code></a>: revenue by tax year and scenario, with every component</li>
<li><a href="../data/act-24/distribution_quintile.csv"><code>distribution_quintile.csv</code></a>: change by fifth of households, {Y} to {last}, with shares paying more and less and credit claimants</li>
<li><a href="../data/act-24/distribution_income_class.csv"><code>distribution_income_class.csv</code></a>: change by income class, {Y} to {last}</li>
<li><a href="../data/act-24/vs_pre_act46.csv"><code>vs_pre_act46.csv</code></a>: Act 46 and Act 24 compared with pre-Act 46 law</li>
<li><a href="../data/act-24/manifest.json"><code>manifest.json</code></a>: run parameters, input vintages and code version</li>
</ul>
""", "method")

    endnotes = section("Endnotes", notes.html(), "endnotes")
    body = hero + s1 + s2 + s3 + s4 + s5 + endnotes
    desc = (f"Act 24 raises about {millions(tot['MID'])} over tax years {Y} to {last} compared with Act 46, "
            f"from households above $1 million and narrower credits, while most households pay a little less.")
    card = {
        "slug": ACT24.slug,
        "category": "current",
        "eyebrow": "Income tax",
        "title": "Act 24",
        "text": "Hawaiʻi’s 2026 income tax law: lower rates for most households, a 13 percent top bracket, and narrower credits.",
        "stat": millions(tot["MID"]),
        "stat_label": f"more revenue over tax years {Y} to {last}",
        "date": long_date(manifest["created_at"]),
        "year": datetime.fromisoformat(manifest["created_at"]).year,
    }
    html_out = page(title="Act 24: Revenue and Distribution | Hawaiʻi Appleseed Estimates",
                    description=desc, body=body, depth=1,
                    year=datetime.fromisoformat(manifest["created_at"]).year)
    return html_out, card


# ---------------------------------------------------------------------------
# Working-family credits page
# ---------------------------------------------------------------------------

def build_working_families() -> tuple[str, dict]:
    d = DATA / WORKING_FAMILIES.slug
    rev = {int(r["tax_year"]): r for r in read_csv(d / "revenue_by_year.csv")}
    cal = {r["check"]: r for r in read_csv(d / "calibration.csv")}
    dist = read_csv(d / "distribution_ty2028.csv")
    fam = read_csv(d / "by_family_type_ty2028.csv")
    pov = read_csv(d / "poverty_ty2028.csv")[0]
    manifest = json.loads((d / "manifest.json").read_text())
    notes = Notes()

    Y = 2028
    years = [y for y in sorted(rev) if y >= Y]
    last = years[-1]
    r = rev[Y]
    persons = pov["persons_into_poverty"]
    kids = pov["children_into_poverty"]

    def about(v: float) -> str:          # survey-based counts: nearest hundred
        return f"{round(v, -2):,.0f}"

    losing_hh = sum(g["households"] * g["pct_households_losing"] / 100 for g in dist)
    single_parent = next(g for g in fam if g["group"] == "Single parent")
    bottom = dist[0]
    top = dist[-1]
    five_year = sum(rev[y]["total_loss_$M"] for y in years)

    T_act163 = ('Hawaiʻi State Legislature, Act 163, Session Laws of Hawaiʻi 2023, §§2, 3 and 5 (repeal and '
                'reenactment on December 31, 2027).')
    T_eitc = ('Hawaiʻi Revised Statutes §235-55.75, refundable earned income tax credit; as amended by Act 114 (2022) '
              'and Act 163 (2023). <a href="https://law.justia.com/codes/hawaii/title-14/chapter-235/section-235-55-75/">law.justia.com</a>')
    T_food = ('Hawaiʻi Revised Statutes §235-55.85, refundable food/excise tax credit; tables before and after Act 163. '
              '<a href="https://law.justia.com/codes/hawaii/title-14/chapter-235/section-235-55-85/">law.justia.com</a>')
    T_2026 = ('Hawaiʻi State Legislature, HB 2306 (2026), which would have extended the Act 163 expansions; '
              'not enacted. Its companion, SB 3125, became Act 24 without the extension. '
              '<a href="https://www.capitol.hawaii.gov/session/measure_indiv.aspx?billtype=HB&amp;billnumber=2306&amp;year=2026">capitol.hawaii.gov</a>')
    T_dotax = ('Hawaiʻi Department of Taxation, “Tax Credits Claimed by Hawaiʻi Taxpayers,” Tax Years 2022 and 2023, '
               'Tables A-1 and A-2. <a href="https://tax.hawaii.gov/stats/">tax.hawaii.gov/stats</a>')
    T_code = (f'Hawaiʻi Appleseed, <code>forecast_working_family_credits.py</code>, Census-Forecaster model, commit '
              f'<code>{esc(manifest["git_sha"])}</code>. <a href="{REPO_URL}/blob/main/forecast_working_family_credits.py">github.com</a>')

    src_model = f"Source: Hawaiʻi Appleseed estimates, Census-Forecaster tax model; tax year {Y}."

    hero = f"""
<section class="ha-est__hero"><div class="ha-est__hero-inner">
<p class="ha-est__eyebrow">Current policy · Tax credits</p>
<h1>Expiring Relief</h1>
<hr class="ha-est__hero-rule">
<p class="ha-est__deck">What Hawaiʻi’s working families lose when the 2023 expansions of the earned income tax credit and the food/excise tax credit expire after 2027, and what renewing them would cost.</p>
<p class="ha-est__meta">Hawaiʻi Appleseed · Model run {esc(long_date(manifest["created_at"]))} · Tax years {Y} to {last}</p>
</div></section>
<div class="ha-est__stats">
<div class="ha-est__stat"><div class="ha-est__stat-num">{millions(r["total_loss_$M"])}</div><div class="ha-est__stat-label"><strong>Less for working families</strong> in tax year {Y}, and what renewal would cost the state.</div></div>
<div class="ha-est__stat"><div class="ha-est__stat-num">{losing_hh / 1000:,.0f},000</div><div class="ha-est__stat-label">Households that <strong>lose part of a credit</strong> in {Y}.</div></div>
<div class="ha-est__stat"><div class="ha-est__stat-num">{dollars(single_parent["avg_loss_per_losing_household"])}</div><div class="ha-est__stat-label">Average loss for a <strong>single-parent household</strong> that loses.</div></div>
<div class="ha-est__stat"><div class="ha-est__stat-num">{about(persons)}</div><div class="ha-est__stat-label">More people in <strong>poverty</strong>, including about {about(kids)} children.</div></div>
</div>"""

    food_rows = [
        ["Under $5,000", "$110", "$220"], ["$5,000 to $10,000", "$100", "$220"],
        ["$10,000 to $15,000", "$85", "$220"], ["$15,000 to $20,000", "$70", "$200"],
        ["$20,000 to $25,000", "$55", "$170"], ["$25,000 to $30,000", "$55", "$140"],
        ["$30,000 to $40,000", "$45*", "$110"], ["$40,000 to $50,000", "$35*", "$90*"],
        ["$50,000 to $60,000", "$0", "$70*"],
    ]
    s1 = section("What Act 163 Did", f"""
{lead("In 2023 the Legislature doubled", f"Hawaiʻi’s two main tax credits for working families.{notes.ref(T_act163)} Act 163 raised the state earned income tax credit from 20 percent to 40 percent of the federal credit, which already went only to people who work.{notes.ref(T_eitc)} It also more than doubled the refundable food/excise tax credit, which offsets the general excise tax low-income households pay on groceries and other necessities, and extended it $10,000 further up the income scale.{notes.ref(T_food)}")}
<p>Both expansions were temporary. Act 163 is repealed on December 31, 2027, and both credits return to their earlier form for tax year {Y}. A 2026 bill to extend them was not enacted.{notes.ref(T_2026)} The earned income tax credit stays refundable, but at 20 percent of the federal credit.</p>
{table(["Income (AGI)", "Before and after 2027", "2023 to 2027"], food_rows,
       caption="Table 1. Food/Excise Tax Credit per Exemption")}
<p class="ha-est__source">Amounts per exemption (the filer, a spouse and each dependent). * Heads of household and married couples only; single filers’ credit ends at $30,000 before and after 2027, and at $40,000 from 2023 to 2027.</p>
""", "act-163")

    s2_series = [("Earned income tax credit", C_PRIMARY, [rev[y]["eitc_loss_$M"] for y in years]),
                 ("Food/excise tax credit", C_SECOND, [rev[y]["food_loss_$M"] for y in years])]
    fig1_label = "Credit dollars lost each year: " + ", ".join(f"{y} {m1(rev[y]['total_loss_$M'])} million" for y in years) + "."
    rrows = [[str(y), m1(rev[y]["eitc_expanded_$M"]), m1(rev[y]["eitc_reverted_$M"]),
              m1(rev[y]["food_expanded_$M"]), m1(rev[y]["food_reverted_$M"]), m1(rev[y]["total_loss_$M"])] for y in years]
    s2 = section("What Families Lose", f"""
{lead("When the expansions expire,", f"working families will receive about {millions(r['total_loss_$M'])} less in tax year {Y}: {millions(r['eitc_loss_$M'])} from the earned income tax credit and {millions(r['food_loss_$M'])} from the food/excise tax credit. Renewing both would cost the state the same amount, about {millions(five_year)} over tax years {Y} to {last}.{notes.ref(T_code)}")}
<p>The food/excise credit’s dollar amounts and income limits are not adjusted for inflation, so as wages rise, fewer households qualify and each credit buys less. Under the expanded table the credit would pay {millions(rev[years[0]]['food_expanded_$M'])} in {Y} and {millions(rev[last]['food_expanded_$M'])} in {last}. The earned income tax credit follows the federal credit, which is indexed.</p>
{figure(1, f"Credit Dollars Working Families Lose Each Year, Hawaiʻi ({Y} to {last})",
        stacked_column_chart([str(y) for y in years], s2_series, label=fig1_label),
        "Source: Hawaiʻi Appleseed estimates, Census-Forecaster tax model. Millions of dollars.", s2_series)}
{table(["Tax year", "EITC, renewed", "EITC, expired", "Food/excise, renewed", "Food/excise, expired", "Lost"], rrows,
       caption="Table 2. State Credits Paid With the Expansions Renewed and Expired ($ Millions)")}
""", "revenue")

    def drow(g, label=None):
        return [label or g["group"], f"{g['households']:,.0f}", pct(g["pct_households_losing"]),
                dollars(g["avg_loss_per_losing_household"]), m1(g["total_loss_$M"])]
    fam_series = [("Average loss", C_PRIMARY, [g["avg_loss_per_losing_household"] for g in fam])]
    labels = {"Lowest 20%": "Lowest 20 percent", "Second 20%": "Second 20 percent", "Middle 20%": "Middle 20 percent",
              "Fourth 20%": "Fourth 20 percent", "Top 20%": "Top 20 percent"}
    s3 = section("Who Loses", f"""
{lead("The loss falls hardest on families with children", f"and the lowest incomes. In {Y}, {pct(bottom['pct_households_losing'])} percent of households in the lowest-income fifth lose part of a credit, an average of {dollars(bottom['avg_loss_per_losing_household'])} each, and that fifth bears {pct(100 * bottom['total_loss_$M'] / r['total_loss_$M'])} percent of the total. Single-parent households that lose give up {dollars(single_parent['avg_loss_per_losing_household'])} on average, as Figure 2 shows.")}
{figure(2, f"Average Loss per Household That Loses a Credit, by Family Type, Hawaiʻi (Tax Year {Y})",
        hbar_chart([g["group"] for g in fam], fam_series, fmt=lambda v: f"${v:,.0f}",
                   label=f"Average loss per household that loses, tax year {Y}: " + "; ".join(f"{g['group']} {dollars(g['avg_loss_per_losing_household'])}" for g in fam) + "."),
        src_model)}
{table(["Family type", "Households", "Percent losing", "Average loss if losing", "Total ($ millions)"],
       [drow(g) for g in fam], caption=f"Table 3. Loss by Family Type, Tax Year {Y}")}
{table(["Household income", "Households", "Percent losing", "Average loss if losing", "Total ($ millions)"],
       [drow(g, labels.get(g["group"])) for g in dist], caption=f"Table 4. Loss by Fifth of Households, Tax Year {Y}")}
<p class="ha-est__source">Households are ranked by the combined income of everyone in them. Many Hawaiʻi households include several tax filers, so a grown child or grandparent with a low income can qualify on their own return in a household near the top of the ranking; that is why {pct(top['pct_households_losing'])} percent of the top fifth lose some credit.</p>
""", "who-loses")

    hoh_r, hoh_e = pov["poverty_rate_renewed_head_of_household"], pov["poverty_rate_expired_head_of_household"]
    s4 = section("More Families in Poverty", f"""
{lead("Losing the expansions pushes", f"an estimated {about(persons)} more people below the poverty line in {Y}, about {about(kids)} of them children, and deepens poverty for families already below it by {millions(pov['poverty_gap_increase_$M'])}. The state poverty rate rises from {pct(100 * pov['poverty_rate_renewed'], 1)} percent to {pct(100 * pov['poverty_rate_expired'], 1)} percent. For single parents and their children it rises from {pct(100 * hoh_r, 1)} percent to {pct(100 * hoh_e, 1)} percent.")}
<p>These figures use the Census Bureau’s Supplemental Poverty Measure, which counts tax credits and public benefits as income and adjusts for Hawaiʻi’s cost of living. Because the counts come from a survey sample, they are rounded to the nearest hundred. The estimate is static: it does not count parents who leave work when the credit shrinks, which the model’s separate analysis of the earned income tax credit finds would add to the total.</p>
""", "poverty")

    vrows = [
        ["State EITC dollars, 2023", f"${cal['TY2023 EITC $M (fit)']['dotax']:,.1f}M", f"${cal['TY2023 EITC $M (fit)']['model']:,.1f}M", "Fitted"],
        ["State EITC claims, 2023", f"{cal['TY2023 EITC claims']['dotax']:,.0f}", f"{cal['TY2023 EITC claims']['model']:,.0f}", "Check"],
        ["Food/excise dollars, 2023", f"${cal['TY2023 food/excise $M (fit)']['dotax']:,.1f}M", f"${cal['TY2023 food/excise $M (fit)']['model']:,.1f}M", "Fitted"],
        ["Food/excise claims, 2023", f"{cal['TY2023 food/excise claims']['dotax']:,.0f}", f"{cal['TY2023 food/excise claims']['model']:,.0f}", "Check"],
        ["Food/excise dollars, 2022 (old table)", f"${cal['TY2022 food/excise $M, prior table (out of sample)']['dotax']:,.1f}M", f"${cal['TY2022 food/excise $M, prior table (out of sample)']['model']:,.1f}M", "Check"],
        ["Food/excise claims, 2022 (old table)", f"{cal['TY2022 food/excise claims, prior table']['dotax']:,.0f}", f"{cal['TY2022 food/excise claims, prior table']['model']:,.0f}", "Check"],
    ]
    s5 = section("How These Estimates Are Made", f"""
{lead("The model builds", "Hawaiʻi tax households from the Census Bureau’s 2024 American Community Survey microdata, with each dependent’s age and relationship, projects their incomes forward with Congressional Budget Office growth rates, and computes the federal earned income tax credit, matched to IRS counts of Hawaiʻi claimants. Each state credit is then computed under both laws from the statute’s own schedules.")}
<p>Not every eligible household claims a credit. The model sets each credit’s claim rate so that 2023, the first year of the expansions, matches what the Department of Taxation actually paid, then holds that rate fixed.{notes.ref(T_dotax)} As a test, the same rate applied to 2022, before the expansion, reproduces that year’s food/excise credit under the old table within 2 percent (Table 5).</p>
{table(["Measure", "Department of Taxation", "Model", ""], vrows, caption="Table 5. Model Against Department of Taxation Records")}
<h3 style="font-size:18px;margin:28px 0 10px">Download the data</h3>
<ul class="ha-est__downloads">
<li><a href="../data/working-family-credits/revenue_by_year.csv"><code>revenue_by_year.csv</code></a>: both credits by tax year, renewed and expired, with claimants</li>
<li><a href="../data/working-family-credits/distribution_ty2028.csv"><code>distribution_ty2028.csv</code></a>: loss by fifth of households</li>
<li><a href="../data/working-family-credits/by_family_type_ty2028.csv"><code>by_family_type_ty2028.csv</code></a>: loss by family type</li>
<li><a href="../data/working-family-credits/poverty_ty2028.csv"><code>poverty_ty2028.csv</code></a>: poverty with the expansions renewed and expired</li>
<li><a href="../data/working-family-credits/calibration.csv"><code>calibration.csv</code></a>: claim rates and the checks in Table 5</li>
<li><a href="../data/working-family-credits/manifest.json"><code>manifest.json</code></a>: run parameters, inputs and code version</li>
</ul>
""", "method")

    endnotes = section("Endnotes", notes.html(), "endnotes")
    body = hero + s1 + s2 + s3 + s4 + s5 + endnotes
    desc = (f"When Act 163’s credit expansions expire after 2027, Hawaiʻi’s working families lose about "
            f"{millions(r['total_loss_$M'])} a year and about {about(persons)} more people fall into poverty.")
    card = {
        "slug": WORKING_FAMILIES.slug,
        "category": "current",
        "eyebrow": "Tax credits",
        "title": "Expiring Relief",
        "text": "The 2023 expansions of the earned income and food/excise tax credits end after 2027. What families lose, and what renewal would cost.",
        "stat": millions(r["total_loss_$M"]),
        "stat_label": f"less for working families in tax year {Y}",
        "date": long_date(manifest["created_at"]),
        "year": datetime.fromisoformat(manifest["created_at"]).year,
    }
    html_out = page(title="Expiring Relief: Working Family Tax Credits | Hawaiʻi Appleseed Estimates",
                    description=desc, body=body, depth=1,
                    year=datetime.fromisoformat(manifest["created_at"]).year)
    return html_out, card


# ---------------------------------------------------------------------------
# hub
# ---------------------------------------------------------------------------

CATEGORIES = (
    ("current", "Current policy",
     "Laws already on the books: what they raise or cost, and who is affected."),
    ("proposed", "Proposed policy",
     "Options before the Legislature or in public debate, scored against current law."),
)


def _card(c: dict) -> str:
    return f"""
<a class="ha-est__card" href="{c['slug']}/">
<p class="ha-est__eyebrow">{esc(c['eyebrow'])}</p>
<h3>{esc(c['title'])}</h3>
<p>{esc(c['text'])}</p>
<div class="ha-est__card-stat">{esc(c['stat'])}</div>
<div class="ha-est__stat-label">{esc(c['stat_label'])}</div>
<div class="ha-est__card-date">Model run {esc(c['date'])}</div>
</a>"""


def build_index(cards: list[dict]) -> str:
    groups = []
    for key, heading, blurb in CATEGORIES:
        mine = [c for c in cards if c["category"] == key]
        if not mine:
            continue
        groups.append(f"""
<section class="ha-est__group" id="{key}">
<div class="ha-est__group-head"><h2>{heading}</h2><hr class="ha-est__h2-rule"><p>{blurb}</p></div>
<div class="ha-est__cards">{"".join(_card(c) for c in mine)}
</div></section>""")
    body = f"""
<section class="ha-est__hero"><div class="ha-est__hero-inner">
<p class="ha-est__eyebrow">Hawaiʻi Appleseed</p>
<h1>Estimates</h1>
<hr class="ha-est__hero-rule">
<p class="ha-est__deck">Revenue and distributional estimates for Hawaiʻi tax and budget policy, from Hawaiʻi Appleseed’s open-source models. Every figure links to the data and code that produced it.</p>
</div></section>{"".join(groups)}"""
    return page(title="Estimates | Hawaiʻi Appleseed", body=body, depth=0, year=max(c["year"] for c in cards),
                description="Revenue and distributional estimates for Hawaiʻi tax and budget policy from Hawaiʻi Appleseed.")


def build(out: Path = SITE) -> list[Path]:
    """Render every page from site/data into `out`. Returns the files written."""
    cg_html, cg_card = build_capital_gains()
    a24_html, a24_card = build_act24()
    wf_html, wf_card = build_working_families()
    written = {
        out / "act-24" / "index.html": a24_html,
        out / "working-family-credits" / "index.html": wf_html,
        out / "capital-gains" / "index.html": cg_html,
        out / "index.html": build_index([a24_card, wf_card, cg_card]),
        out / ".nojekyll": "",
    }
    for path, text in written.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    return list(written)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--import-runs", nargs="*", metavar="SLUG",
                    help="copy fresh outputs from runs/ into site/data/ first "
                         f"(all estimates, or only the named ones: {', '.join(e.slug for e in ESTIMATES)})")
    args = ap.parse_args()
    if args.import_runs is not None:
        for est in ESTIMATES:
            if not args.import_runs or est.slug in args.import_runs:
                import_runs(est)
    for p in build():
        print(f"wrote {p.relative_to(REPO)}")


if __name__ == "__main__":
    main()
