"""Build the public estimates site (GitHub Pages) from published model outputs.

Usage:
  python scripts/build_site.py                 # regenerate site/ from site/data/
  python scripts/build_site.py --import-runs   # first copy fresh outputs from runs/

Two steps, on purpose. Model runs write to runs/ (gitignored, and the capital
gains run alone takes ~25 minutes against a local tax-unit cache), so CI can
never reproduce them. `--import-runs` copies a run's outputs into site/data/,
where they are committed and reviewed like code. Every page is then rendered
from those committed copies only, so the numbers in the prose, the charts, and
the downloadable CSVs cannot disagree, and `tests/test_site_build.py` can check
that the committed HTML is exactly what the committed data produces.

The .github/workflows/pages.yml workflow deploys site/ as-is; it does not build.

Pages are static HTML with CSS bar charts: no JavaScript, no external
requests beyond Google Fonts. Brand tokens are in site/assets/site.css.
"""
from __future__ import annotations

import argparse
import contextlib
import csv
import html
import json
import shutil
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SITE = REPO / "site"
DATA = SITE / "data"
REPO_URL = "https://github.com/Hawaii-Appleseed/Census-Forecaster"

GENERATED = "<!-- GENERATED by scripts/build_site.py from site/data/. Do not hand-edit. -->"

# Chart colors: brand teal-deep and teal.
C_PRIMARY = "#52796F"
C_SECOND = "#84A98C"


# ---------------------------------------------------------------------------
# data import
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Estimate:
    slug: str
    run_dir: str          # under runs/
    files: tuple[str, ...]


CAPITAL_GAINS = Estimate(
    slug="capital-gains",
    run_dir="cg_rate_options",
    files=(
        "revenue_by_year.csv",
        "distribution_ty2027_act24.csv",
        "distribution_ty2026_act46.csv",
        "nonresident_addon.csv",
        "anchor_check.csv",
        "manifest.json",
    ),
)
ESTIMATES = (CAPITAL_GAINS,)


def import_runs(est: Estimate) -> None:
    src = REPO / "runs" / est.run_dir
    dst = DATA / est.slug
    missing = [f for f in est.files if not (src / f).exists()]
    if missing:
        raise SystemExit(f"{src} is missing {missing}; run the model first.")
    dst.mkdir(parents=True, exist_ok=True)
    for f in est.files:
        shutil.copy2(src / f, dst / f)
    manifest = json.loads((dst / "manifest.json").read_text())
    manifest["published_at"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
    (dst / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"imported {len(est.files)} files: runs/{est.run_dir} -> site/data/{est.slug}")


def read_csv(path: Path) -> list[dict]:
    with path.open(newline="") as fh:
        rows = list(csv.DictReader(fh))
    for r in rows:
        for k, v in r.items():
            with contextlib.suppress(TypeError, ValueError):
                r[k] = float(v)
    return rows


# ---------------------------------------------------------------------------
# formatting
# ---------------------------------------------------------------------------

def esc(s) -> str:
    return html.escape(str(s), quote=True)


def millions(v: float) -> str:
    """Prose: '$47 million'."""
    return f"${v:,.0f} million"


def m1(v: float) -> str:
    """Tables: millions to one decimal."""
    return f"{v:,.1f}"


def dollars(v: float) -> str:
    if v < 0.5:
        return "$0"
    return f"${v:,.0f}"


def pct(v: float, digits: int = 0) -> str:
    return f"{v:.{digits}f}"


def income_range(lo: float, hi: float, last: bool) -> str:
    def k(v):
        return f"${v / 1000:,.0f}K" if v < 1e6 else f"${v / 1e6:,.1f}M"
    if lo < 1:
        return f"Under {k(hi)}"
    if last:
        return f"{k(lo)} and up"
    return f"{k(lo)} to {k(hi)}"


def long_date(iso: str) -> str:
    d = datetime.fromisoformat(iso)
    return f"{d:%B} {d.day}, {d.year}"


# ---------------------------------------------------------------------------
# charts
#
# HTML/CSS bars rather than SVG: an SVG scales its text with the chart, so
# labels legible on a desktop shrink to ~7px on a phone. Bars sized in percent
# keep the text at its CSS size at every width. Each chart is one role="img"
# with a full-sentence aria-label; the data is also in a table or the CSVs.
# ---------------------------------------------------------------------------

Series = list[tuple[str, str, list[float]]]   # (name, color, values)


def _money_m(v: float) -> str:
    return f"${v:,.0f}M"


def hbar_chart(categories: list[str], series: Series, *, label: str, fmt=_money_m) -> str:
    """Horizontal grouped bars, value printed at each bar's end."""
    vmax = max(max(vals) for _, _, vals in series) or 1
    groups = []
    for i, cat in enumerate(categories):
        bars = "".join(
            f'<div class="ha-est__hbar-row"><span class="ha-est__hbar" '
            f'style="width:{max(100 * vals[i] / vmax, 0.4):.2f}%;background:{color}"></span>'
            f'<span class="ha-est__hbar-val">{esc(fmt(vals[i]))}</span></div>'
            for _, color, vals in series)
        groups.append(f'<div class="ha-est__hbar-group"><div class="ha-est__hbar-cat">{esc(cat)}</div>'
                      f'<div class="ha-est__hbar-bars">{bars}</div></div>')
    return (f'<div class="ha-est__chart ha-est__chart--h" role="img" aria-label="{esc(label)}">'
            f'<div aria-hidden="true">{"".join(groups)}</div></div>')


def column_chart(categories: list[str], series: Series, *, label: str, fmt=_money_m) -> str:
    """Vertical grouped columns with a value label on each column."""
    vmax = max(max(vals) for _, _, vals in series) or 1
    slots = []
    for i, cat in enumerate(categories):
        cols = "".join(
            f'<div class="ha-est__col"><span class="ha-est__col-val">{esc(fmt(vals[i]))}</span>'
            f'<span class="ha-est__col-bar" style="height:{100 * vals[i] / vmax:.2f}%;background:{color}"></span></div>'
            for _, color, vals in series)
        slots.append(f'<div class="ha-est__col-slot"><div class="ha-est__col-bars">{cols}</div>'
                     f'<div class="ha-est__col-cat">{esc(cat)}</div></div>')
    return (f'<div class="ha-est__chart ha-est__chart--v" role="img" aria-label="{esc(label)}">'
            f'<div class="ha-est__col-grid" aria-hidden="true">{"".join(slots)}</div></div>')

def legend(series: list[tuple[str, str, list[float]]]) -> str:
    items = "".join(f'<span><span class="ha-est__swatch" style="background:{c}"></span>{esc(n)}</span>'
                    for n, c, _ in series)
    return f'<div class="ha-est__legend" aria-hidden="true">{items}</div>'


def figure(num: int, caption: str, chart: str, source: str, series=None, note_ref: str = "") -> str:
    leg = legend(series) if series else ""
    return (f'<figure class="ha-est__figure" id="figure-{num}">'
            f'<p class="ha-est__figcap">Figure {num}. {caption}{note_ref}</p>{leg}{chart}'
            f'<p class="ha-est__source">{source}</p></figure>')


def table(headers: list[str], rows: list[list[str]], *, caption: str, em_rows: set[int] = frozenset()) -> str:
    th = "".join(f'<th scope="col">{h}</th>' for h in headers)
    body = []
    for i, r in enumerate(rows):
        cls = ' class="ha-est__row-em"' if i in em_rows else ""
        cells = "".join((f'<th scope="row">{c}</th>' if k == 0 else f"<td>{c}</td>") for k, c in enumerate(r))
        body.append(f"<tr{cls}>{cells}</tr>")
    # Caption sits outside the scroll wrapper so a wide table scrolls without clipping it.
    return (f'<p class="ha-est__figcap">{caption}</p><div class="ha-est__table-wrap">'
            f'<table><thead><tr>{th}</tr></thead><tbody>{"".join(body)}</tbody></table></div>')


# ---------------------------------------------------------------------------
# page shell
# ---------------------------------------------------------------------------

def page(*, title: str, description: str, body: str, depth: int, year: int) -> str:
    up = "../" * depth
    return f"""<!DOCTYPE html>
{GENERATED}
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(title)}</title>
<meta name="description" content="{esc(description)}">
<meta property="og:title" content="{esc(title)}">
<meta property="og:description" content="{esc(description)}">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Manrope:wght@500;600;700;800&family=Poppins:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500&display=swap">
<link rel="stylesheet" href="{up}assets/okina.css">
<link rel="stylesheet" href="{up}assets/site.css">
</head>
<body class="ha-est">
<header class="ha-est__nav"><div class="ha-est__nav-inner">
<a href="https://www.hiappleseed.org"><img src="{up}assets/appleseed-logo-cropped.png" alt="Hawaiʻi Appleseed Center for Law &amp; Economic Justice"></a>
<a class="ha-est__nav-link" href="{up}index.html">All estimates</a>
</div></header>
<main>
{body}
</main>
<footer class="ha-est__footer"><div class="ha-est__footer-inner">
<img src="{up}assets/appleseed-footer-logo-white.png" alt="Hawaiʻi Appleseed">
<p>Estimates from Hawaiʻi Appleseed’s open-source tax and census models. Code, data, and methodology: <a href="{REPO_URL}">{REPO_URL.removeprefix("https://")}</a>.</p>
<p>Copyright © {year} Hawaiʻi Appleseed Center for Law &amp; Economic Justice. All rights reserved. 733 Bishop Street, Suite 1180, Honolulu, HI 96813</p>
</div></footer>
</body>
</html>
"""


def section(heading: str, body: str, sid: str) -> str:
    return (f'<section class="ha-est__section" id="{sid}"><div class="ha-est__section-inner">'
            f'<h2>{heading}</h2><hr class="ha-est__h2-rule">{body}</div></section>')


def lead(words: str, rest: str) -> str:
    """The house lead-in: a section's first few words set in caps."""
    return f'<p><span class="ha-est__lead-in">{words.upper()}</span> {rest}</p>'


class Notes:
    """Numbered endnotes; `ref` returns the superscript marker."""

    def __init__(self):
        self.items: list[str] = []

    def ref(self, text: str) -> str:
        if text in self.items:          # repeat cite: same number, no second anchor id
            n = self.items.index(text) + 1
            return f'<sup><a href="#note-{n}">{n}</a></sup>'
        self.items.append(text)
        n = len(self.items)
        return f'<sup><a href="#note-{n}" id="ref-{n}">{n}</a></sup>'

    def html(self) -> str:
        lis = "".join(f'<li id="note-{i}">{t}</li>' for i, t in enumerate(self.items, 1))
        return f'<ol class="ha-est__endnotes">{lis}</ol>'


# ---------------------------------------------------------------------------
# capital gains page
# ---------------------------------------------------------------------------

GROUPS_SHORT = {"Lowest 20%": "Lowest 20 percent", "Second 20%": "Second 20 percent",
                "Middle 20%": "Middle 20 percent", "Fourth 20%": "Fourth 20 percent",
                "Next 15%": "Next 15 percent", "Next 4%": "Next 4 percent", "Top 1%": "Top 1 percent"}


def _rev(rows, year, law, option, variant="central"):
    for r in rows:
        if (int(r["tax_year"]), r["law"], r["option"], r["top_share"]) == (year, law, option, variant):
            return r
    raise KeyError((year, law, option, variant))


def _nr(rows, year, option, kind):
    for r in rows:
        if (int(r["tax_year"]), r["option"], r["kind"]) == (year, option, kind):
            return r
    raise KeyError((year, option, kind))


def build_capital_gains() -> tuple[str, dict]:
    d = DATA / CAPITAL_GAINS.slug
    rev = read_csv(d / "revenue_by_year.csv")
    dist = read_csv(d / "distribution_ty2027_act24.csv")
    nr = read_csv(d / "nonresident_addon.csv")
    manifest = json.loads((d / "manifest.json").read_text())
    p = manifest["params"]
    notes = Notes()

    Y = 2027
    years = sorted({int(r["tax_year"]) for r in rev if r["law"] == "act24"})
    cap_new = p["options"]["cap9"] * 100
    cap_cur = p["cap_current"] * 100
    beta = p["beta"]

    c9 = _rev(rev, Y, "act24", "cap9")
    od = _rev(rev, Y, "act24", "ordinary")
    c9_46 = _rev(rev, Y, "act46", "cap9")
    od_46 = _rev(rev, Y, "act46", "ordinary")
    od_lo = min(_rev(rev, Y, "act24", "ordinary", v)["behavioral_M"] for v in ("low", "model"))
    od_hi = max(_rev(rev, Y, "act24", "ordinary", v)["behavioral_M"] for v in ("low", "model"))
    c9_lo = min(_rev(rev, Y, "act24", "cap9", v)["behavioral_M"] for v in ("low", "model"))
    c9_hi = max(_rev(rev, Y, "act24", "cap9", v)["behavioral_M"] for v in ("low", "model"))
    t26 = {o: _rev(rev, 2026, "act46", o) for o in ("cap9", "ordinary")}
    itep = {"cap9": 44.0, "ordinary": 85.0}
    top = next(r for r in dist if r["group"] == "Top 1%")
    nxt4 = next(r for r in dist if r["group"] == "Next 4%")
    bottom60_zero = all(r["total_ordinary_behavioral_M"] < 0.005 for r in dist[:3])
    act24_effect = od["behavioral_M"] - od_46["behavioral_M"]
    nr_od = _nr(nr, Y, "ordinary", "behavioral")
    nr_c9 = _nr(nr, Y, "cap9", "behavioral")
    last = years[-1]
    od_last = _rev(rev, last, "act24", "ordinary")["behavioral_M"]
    c9_last = _rev(rev, last, "act24", "cap9")["behavioral_M"]

    T_act24 = (
        'Hawaiʻi State Legislature, “SB 3125 SD2 HD2 CD2,” enacted as Act 24, Session Laws of Hawaiʻi 2026, '
        'May 21, 2026. <a href="https://www.capitol.hawaii.gov/session/measure_indiv.aspx?billtype=SB&amp;billnumber=3125&amp;year=2026">'
        'capitol.hawaii.gov</a>')
    T_hrs = (
        'Hawaiʻi Revised Statutes §235-51(f), alternative tax on net capital gain. '
        '<a href="https://www.capitol.hawaii.gov/hrscurrent/Vol04_Ch0201-0257/HRS0235/HRS_0235-0051.htm">capitol.hawaii.gov</a>')
    T_blog = (
        'Thomas, Devin, “Hawaiʻi’s two-tier tax system: How the rich use a glaring loophole to pay less,” '
        'Hawaiʻi Appleseed Center for Law &amp; Economic Justice, November 13, 2025. '
        '<a href="https://www.hiappleseed.org/blog/hawaii-two-tier-tax-system-glaring-loophole-rich-pay-less">hiappleseed.org</a>. '
        'Its figures were produced by the Institute on Taxation and Economic Policy.')
    T_dotax = (
        'Hawaiʻi Department of Taxation, “Hawaiʻi Individual Income Tax Statistics,” tax years 2018 to 2022 editions, '
        'Tables 21, A-1 and A-8. <a href="https://tax.hawaii.gov/stats/">tax.hawaii.gov/stats</a>')
    T_code = (
        f'Hawaiʻi Appleseed, <code>forecast_cg_rate_options.py</code>, Census-Forecaster model, commit '
        f'<code>{esc(manifest["git_sha"])}</code>. <a href="{REPO_URL}/blob/main/forecast_cg_rate_options.py">github.com</a>')
    T_cbo = (
        f'Congressional Budget Office, economic projections, {esc(p["cbo_vintage"])} vintage, capital gains realizations, '
        'adjusted to Hawaiʻi. <a href="https://www.cbo.gov/topics/budget/economic-projections">cbo.gov</a>')

    src_model = (f"Source: Hawaiʻi Appleseed estimates, Census-Forecaster tax model; resident filers only; "
                 f"tax year {Y}.")

    # --- hero + stats
    hero = f"""
<section class="ha-est__hero"><div class="ha-est__hero-inner">
<p class="ha-est__eyebrow">Estimates · Capital gains</p>
<h1>Closing the Gap</h1>
<hr class="ha-est__hero-rule">
<p class="ha-est__deck">What Hawaiʻi would raise by taxing capital gains at {pct(cap_new)} percent, or at the same rates as wages, now that Act 24 has raised the top rate on work to 13 percent.</p>
<p class="ha-est__meta">Hawaiʻi Appleseed · Model run {esc(long_date(manifest["created_at"]))} · Tax years {years[0]} to {last}</p>
</div></section>
<div class="ha-est__stats">
<div class="ha-est__stat"><div class="ha-est__stat-num">{millions(od["behavioral_M"])}</div><div class="ha-est__stat-label"><strong>Tax gains as ordinary income.</strong> Revenue in tax year {Y}, residents.</div></div>
<div class="ha-est__stat"><div class="ha-est__stat-num">{millions(c9["behavioral_M"])}</div><div class="ha-est__stat-label"><strong>Raise the cap to {pct(cap_new)} percent.</strong> Revenue in tax year {Y}, residents.</div></div>
<div class="ha-est__stat"><div class="ha-est__stat-num">{pct(top["share_ordinary_behavioral"] * 100)} percent</div><div class="ha-est__stat-label">Share of the ordinary-rates increase paid by the <strong>top 1 percent</strong> of households.</div></div>
<div class="ha-est__stat"><div class="ha-est__stat-num">{13 - cap_cur:.2f} points</div><div class="ha-est__stat-label">Gap between the top rate on wages and the rate on capital gains under <strong>Act 24</strong>.</div></div>
</div>"""

    # --- section 1: the gap
    s1_series = [("Act 46 brackets", C_SECOND, [c9_46["behavioral_M"], od_46["behavioral_M"]]),
                 ("Act 24 brackets", C_PRIMARY, [c9["behavioral_M"], od["behavioral_M"]])]
    s1 = section("The Gap Act 24 Widened", f"""
{lead("Hawaiʻi taxes most income", f"on a graduated schedule, but long-term capital gains get a special ceiling. Under the alternative tax in state law, net capital gains are taxed at no more than {pct(cap_cur, 2)} percent, however high the filer’s other income.{notes.ref(T_hrs)}")}
<p>Act 24 of 2026 added a 13 percent bracket above $1 million of taxable income for joint filers ($750,000 for heads of household, $500,000 for single filers) and raised the rates between $350,000 and $1 million.{notes.ref(T_act24)} It left the capital gains ceiling where it was. The distance between the top rate on wages and the rate on capital gains therefore grew from 3.75 points to 5.75 points.</p>
<p>That matters for what closing the gap would raise. Taxing gains at ordinary rates now brings gains up to 13 percent rather than 11 percent, so the same option is worth more under Act 24 than it was under the Act 46 brackets it replaced. Figure 1 compares the two. A {pct(cap_new)} percent cap is nearly unchanged, because it does not depend on the ordinary rates.</p>
{figure(1, f"Revenue From Each Option Under Act 46 and Act 24 Brackets, Hawaiʻi (Tax Year {Y})",
        hbar_chart([f"{pct(cap_new)} percent cap", "Ordinary rates"], s1_series, label=f"Tax year {Y} revenue by bracket schedule: 9 percent cap {m1(c9_46['behavioral_M'])} million under Act 46 and {m1(c9['behavioral_M'])} million under Act 24; ordinary rates {m1(od_46['behavioral_M'])} million under Act 46 and {m1(od['behavioral_M'])} million under Act 24."),
        src_model + " Millions of dollars, with a realization response.", s1_series, notes.ref(T_code))}
<p>Under Act 24, taxing capital gains as ordinary income would raise about {millions(act24_effect)} more in tax year {Y} than the same change would have under the Act 46 brackets.</p>
""", "gap")

    # --- section 2: revenue
    s2_series = [(f"{pct(cap_new)} percent cap", C_SECOND, [_rev(rev, y, "act24", "cap9")["behavioral_M"] for y in years]),
                 ("Ordinary rates", C_PRIMARY, [_rev(rev, y, "act24", "ordinary")["behavioral_M"] for y in years])]
    rows = []
    for y in years:
        a, b = _rev(rev, y, "act24", "cap9"), _rev(rev, y, "act24", "ordinary")
        rows.append([str(y), m1(a["static_M"]), m1(a["behavioral_M"]), m1(b["static_M"]), m1(b["behavioral_M"])])
    s2 = section("What Each Option Would Raise", f"""
{lead("Taxing capital gains as ordinary income", f"would raise an estimated {millions(od['behavioral_M'])} from Hawaiʻi residents in tax year {Y}, the first year a bill passed in 2027 could reach. Raising the ceiling to {pct(cap_new)} percent would raise about {millions(c9['behavioral_M'])}.")}
<p>Both figures account for investors selling less when the tax on selling rises. The model reduces realized gains by {beta:.0f} percent for each point the state rate goes up. Without that response, the estimates would be {millions(od['static_M'])} and {millions(c9['static_M'])}. Figure 2 shows how revenue grows through {last} as gains grow with the economy.{notes.ref(T_cbo)}</p>
{figure(2, f"Revenue by Tax Year Under Act 24, Hawaiʻi ({years[0]} to {last})",
        column_chart([str(y) for y in years], s2_series, label=f"Revenue by tax year under Act 24. Ordinary rates rise from {m1(od['behavioral_M'])} million in {Y} to {m1(od_last)} million in {last}; the {pct(cap_new)} percent cap rises from {m1(c9['behavioral_M'])} million to {m1(c9_last)} million."),
        "Source: Hawaiʻi Appleseed estimates, Census-Forecaster tax model; resident filers only. Millions of dollars, with a realization response.", s2_series)}
{table(["Tax year", f"{pct(cap_new)}% cap, static", f"{pct(cap_new)}% cap, with response", "Ordinary, static", "Ordinary, with response"],
       rows, caption="Table 1. Resident Revenue by Tax Year Under Act 24 ($ Millions)", em_rows={0})}
<div class="ha-est__callout"><p><strong>How sure are these numbers?</strong> The biggest uncertainty is how gains split between filers just above and far above $1 million, since the top bracket applies only to the second group. State data puts about {p["top_share_variants"]["central"] * 100:.0f} percent of the gains in the top income class above $1 million. Moving that between {p["top_share_variants"]["low"] * 100:.0f} percent and the roughly 92 percent that national data implies gives a range of {millions(od_lo)} to {millions(od_hi)} for ordinary rates in {Y}, and {millions(c9_lo)} to {millions(c9_hi)} for the {pct(cap_new)} percent cap.</p></div>
""", "revenue")

    # --- section 3: distribution
    grp = [GROUPS_SHORT.get(r["group"], r["group"]) for r in dist]
    # The chart folds the bottom three quintiles into one bar when they pay nothing
    # (seven rows of 0.0% bury the point); Table 2 still lists every group.
    fold = 3 if bottom60_zero else 0
    chart_grp = (["Bottom 60 percent"] if fold else []) + grp[fold:]

    def _shares(col):
        vals = [r[col] * 100 for r in dist]
        return ([sum(vals[:fold])] if fold else []) + vals[fold:]
    s3_series = [(f"{pct(cap_new)} percent cap", C_SECOND, _shares("share_cap9_behavioral")),
                 ("Ordinary rates", C_PRIMARY, _shares("share_ordinary_behavioral"))]
    drows = []
    for i, r in enumerate(dist):
        drows.append([grp[i], income_range(r["tci_lo"], r["tci_hi"], i == len(dist) - 1), f"{r['households']:,.0f}",
                      dollars(r["avg_cap9_behavioral"]), dollars(r["avg_ordinary_behavioral"]),
                      pct(r["pct_hh_up_ordinary_behavioral"]), pct(r["share_ordinary_behavioral"] * 100, 1)])
    s3 = section("Who Would Pay", f"""
{lead("Almost all of the new revenue", f"would come from the highest-income households, because that is where capital gains are. Under ordinary rates, the top 1 percent of households, those with income above about {income_range(top['tci_lo'], 0, True).split(' ')[0]}, would pay {pct(top['share_ordinary_behavioral'] * 100)} percent of the increase, an average of {dollars(top['avg_ordinary_behavioral'])} each. The next 4 percent would pay {pct(nxt4['share_ordinary_behavioral'] * 100)} percent.")}
<p>{"Households in the bottom 60 percent would pay nothing more under either option: their income is taxed at rates below the " + pct(cap_cur, 2) + " percent ceiling, so the ceiling does not lower their tax today, and raising or repealing it changes nothing for them." if bottom60_zero else ""} Figure 3 shows each group’s share of the total, and Table 2 the average change per household.</p>
{figure(3, f"Share of the Tax Increase by Income Group, Hawaiʻi (Tax Year {Y})",
        hbar_chart(chart_grp, s3_series, label=f"Share of the tax increase by income group, tax year {Y}. The top 1 percent pays {pct(top['share_ordinary_behavioral'] * 100)} percent under ordinary rates.", fmt=lambda v: f"{v:.1f}%", ),
        src_model + " Groups rank all resident households by income; each holds the stated share of households.", s3_series)}
{table(["Income group", "Income range", "Households", f"Avg. change, {pct(cap_new)}% cap", "Avg. change, ordinary", "Percent with increase (ordinary)", "Share of total (ordinary, percent)"],
       drows, caption=f"Table 2. Average Tax Change by Income Group Under Act 24, Tax Year {Y}")}
""", "who-pays")

    # --- section 4: check vs ITEP
    crow = [[f"{pct(cap_new)} percent cap", millions(itep["cap9"]), millions(t26["cap9"]["static_M"]), millions(t26["cap9"]["behavioral_M"])],
            ["Ordinary rates", millions(itep["ordinary"]), millions(t26["ordinary"]["static_M"]), millions(t26["ordinary"]["behavioral_M"])]]
    s4 = section("Checking Against Earlier Estimates", f"""
{lead("In November 2025,", f"Hawaiʻi Appleseed published estimates from the Institute on Taxation and Economic Policy for the same two options, for tax year 2026 under the Act 46 brackets then in law: {millions(itep['cap9'])} for a {pct(cap_new)} percent cap and {millions(itep['ordinary'])} for ordinary rates.{notes.ref(T_blog)}")}
<p>Scored on the same year and brackets, this model lands within a few million dollars of both once the realization response is included, as Table 3 shows. That agreement is the basis for trusting the Act 24 estimates above, which use the same method with the new brackets.</p>
{table(["Option", "ITEP (2025)", "This model, static", "This model, with response"], crow,
       caption="Table 3. Tax Year 2026 Resident Revenue Under Act 46 Brackets")}
""", "check")

    # --- section 5: nonresidents
    s5 = section("Gains Earned by Nonresidents", f"""
{lead("The figures above count residents only,", f"to match the earlier estimates. Nonresidents who sell Hawaiʻi property or hold interests in Hawaiʻi businesses also pay the alternative tax on those gains. In a typical year, the model estimates they would add about {millions(nr_od['typical_year_M'])} to the ordinary-rates option and {millions(nr_c9['typical_year_M'])} to the {pct(cap_new)} percent cap in tax year {Y}.")}
<p>Nonresident gains swing widely from year to year. At tax year 2022 levels, when nonresident gains spiked, the add-on would be {millions(nr_od['ty2022_level_M'])} and {millions(nr_c9['ty2022_level_M'])}. Both figures include the realization response.{notes.ref(T_dotax)}</p>
""", "nonresidents")

    # --- section 6: method + downloads
    base = manifest["inputs"]["tax_unit_cache"]
    s6 = section("How These Estimates Are Made", f"""
{lead("The model builds", f"a synthetic population of about {base['n_units']:,} Hawaiʻi tax units from the Census Bureau’s American Community Survey microdata ({esc(base['pums'])}), calibrated to state tax data and projected forward with Congressional Budget Office growth rates. Filers with income above $1 million, whom survey data miss, are added from IRS and state tax statistics.")}
<p>Capital gains are anchored to the Department of Taxation’s count of resident long-term gains eligible for the alternative rate, by income class, then grown each year.{notes.ref(T_dotax)} Tax is computed as the statute defines the alternative tax, not with the simple shortcut of taxing gains at the lower of the bracket rate and the ceiling. The realization response and the split of gains at the top are the two assumptions that move the estimates most, and both are stated above.</p>
<p>The full method, including every parameter, is documented in the source code.{notes.ref(T_code)}</p>
<h3 style="font-size:18px;margin:28px 0 10px">Download the data</h3>
<ul class="ha-est__downloads">
<li><a href="../data/capital-gains/revenue_by_year.csv"><code>revenue_by_year.csv</code></a> — revenue by tax year, bracket schedule, option and top-share assumption</li>
<li><a href="../data/capital-gains/distribution_ty2027_act24.csv"><code>distribution_ty2027_act24.csv</code></a> — tax change by income group, tax year 2027, Act 24</li>
<li><a href="../data/capital-gains/distribution_ty2026_act46.csv"><code>distribution_ty2026_act46.csv</code></a> — the same for tax year 2026 under Act 46</li>
<li><a href="../data/capital-gains/nonresident_addon.csv"><code>nonresident_addon.csv</code></a> — nonresident add-on by year and option</li>
<li><a href="../data/capital-gains/anchor_check.csv"><code>anchor_check.csv</code></a> — model gains against Department of Taxation targets, by income class</li>
<li><a href="../data/capital-gains/manifest.json"><code>manifest.json</code></a> — run parameters, input vintages and code version</li>
</ul>
""", "method")

    endnotes = section("Endnotes", notes.html(), "endnotes")
    body = hero + s1 + s2 + s3 + s4 + s5 + s6 + endnotes
    desc = (f"Taxing capital gains as ordinary income would raise about {millions(od['behavioral_M'])} from Hawaiʻi residents "
            f"in tax year {Y}; a {pct(cap_new)} percent cap about {millions(c9['behavioral_M'])}.")
    card = {
        "slug": CAPITAL_GAINS.slug,
        "eyebrow": "Capital gains",
        "title": "Closing the Gap",
        "text": f"What taxing capital gains at {pct(cap_new)} percent, or at ordinary rates, would raise under Act 24.",
        "stat": f"${c9['behavioral_M']:,.0f} to {millions(od['behavioral_M'])}",
        "stat_label": f"per year, tax year {Y}",
        "date": long_date(manifest["created_at"]),
        "year": datetime.fromisoformat(manifest["created_at"]).year,
    }
    html_out = page(title="Closing the Gap: Capital Gains Options | Hawaiʻi Appleseed Estimates",
                    description=desc, body=body, depth=1,
                    year=datetime.fromisoformat(manifest["created_at"]).year)
    return html_out, card


# ---------------------------------------------------------------------------
# hub
# ---------------------------------------------------------------------------

def build_index(cards: list[dict]) -> str:
    items = "".join(f"""
<a class="ha-est__card" href="{c['slug']}/">
<p class="ha-est__eyebrow">{esc(c['eyebrow'])}</p>
<h3>{esc(c['title'])}</h3>
<p>{esc(c['text'])}</p>
<div class="ha-est__card-stat">{esc(c['stat'])}</div>
<div class="ha-est__stat-label">{esc(c['stat_label'])}</div>
<div class="ha-est__card-date">Model run {esc(c['date'])}</div>
</a>""" for c in cards)
    body = f"""
<section class="ha-est__hero"><div class="ha-est__hero-inner">
<p class="ha-est__eyebrow">Hawaiʻi Appleseed</p>
<h1>Estimates</h1>
<hr class="ha-est__hero-rule">
<p class="ha-est__deck">Revenue and distributional estimates for Hawaiʻi tax and budget policy, from Hawaiʻi Appleseed’s open-source models. Every figure links to the data and code that produced it.</p>
</div></section>
<div class="ha-est__cards">{items}
</div>"""
    return page(title="Estimates | Hawaiʻi Appleseed", body=body, depth=0, year=max(c["year"] for c in cards),
                description="Revenue and distributional estimates for Hawaiʻi tax and budget policy from Hawaiʻi Appleseed.")


def build(out: Path = SITE) -> list[Path]:
    """Render every page from site/data into `out`. Returns the files written."""
    cg_html, cg_card = build_capital_gains()
    written = {
        out / "capital-gains" / "index.html": cg_html,
        out / "index.html": build_index([cg_card]),
        out / ".nojekyll": "",
    }
    for path, text in written.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    return list(written)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--import-runs", action="store_true", help="copy fresh outputs from runs/ into site/data/ first")
    args = ap.parse_args()
    if args.import_runs:
        for est in ESTIMATES:
            import_runs(est)
    for p in build():
        print(f"wrote {p.relative_to(REPO)}")


if __name__ == "__main__":
    main()
